### ISSUE TITLE
Naomi/System SP/Atomiswave support

### ISSUE THREAD

**Issue by GeekyFerret** [inolen/redream#100]
Would it be possible to add support for Sega Naomi, Sega System SP, and Sammy Atomiswave?

These are arcade systems that use Dreamcast hardware.
[Naomi](http://www.system16.com/hardware.php?id=721)
[Naomi 2](http://www.system16.com/hardware.php?id=725)
[System SP](http://www.system16.com/hardware.php?id=732)
[Atomiswave](http://www.system16.com/hardware.php?id=812)

**Comment by inolen** [comment]
Hey, at some point in the distant further this may be pursued.

With that said, I'm going to close this in order to focus on more certain issues and features.
