### ISSUE TITLE
[*nix] disc_create tests should be case insensitive

### ISSUE THREAD

**Issue by BPaden** [inolen/redream#103]
If you try to load a CDI/GDI file made on Windows using an extension with caps, disc_create will fail. This should also be a problem on OS X if a case-sensitive filesystem is used. On linux with glibc you can replace strstr with strcasestr, but this is probably not available on OS X/BSD and definitely not visual studio.

I threw together a fallback if you want to toss it in your string.c. I'd make a pull request, but I'd have to set everything up and test with -std=c11 to make sure the fallback is used, and I don't know cmake.

```c
char *strcasestr(const char *haystack, const char *needle) {
  for (; *haystack != '\0'; haystack++) {
    if (*needle == '\0') {
      break;
    }
    if (tolower((unsigned char)*haystack) == tolower((unsigned char)*needle)) {
      const char *haystack_ptr = haystack;
      for (const char *needle_itr = needle; ; needle_itr++) {
        if (*needle_itr == '\0') {
          return (char *)haystack_ptr;
        }
        if (tolower((unsigned char)*haystack) != tolower((unsigned char)*needle_itr)) {
          break;
        }
        haystack++;
      }
    }
  }
  return NULL;
}
```

**Comment by inolen** [comment]
Are you saying these should be case insensitive because there are a bunch of GDIs floating around where there are mismatched cases that it would be nice to support?

That withstanding, these just look like invalid GDIs. The same problem would happen if say, someone created a GDI on Linux with a ? in the filename.

**Comment by BPaden** [comment]
Not quite. Having the file extension in caps is **not** wrong, but having a ? in the extension obviously is. To test, open up your file manager (assuming you use Linux) and change the name of a png or PNG or zip to ZIP, and you'll notice that it still understands what the filetype is. This is the correct behaviour for compatibility with Windows/DOS tools.

**Comment by inolen** [comment]
@BPaden my point was, using a ? in a filename is valid on Linux, but not on Windows. You could create the GDI on Linux, but there'd be no way to sanitize loading it such that it worked on Windows as it's incompatible. This is how I see creating a GDI on Windows that relies on its case-insensitivity and trying to load it in Linux.

How a program interprets file extensions is up to it, but that doesn't change the fact that in a case-sensitive filesystem `FOOBAR` and `foobar` or `foobar.TXT` and `foobar.txt` are two entirely different files.

Pending there being a large volume of GDIs out in the wild that have mismatched casing causing users confusing errors, I wouldn't want to special case this.
