### ISSUE TITLE
Unable to make GL context current

### ISSUE THREAD

**Issue by Marc34** [inolen/redream#109]
Capcom vs. SNK, Ecco the Dolphin and F1 World Grand Prix II crash with this message : 

Check failed: res == 0
[/redream-master/src/host/sdl_host.c:278]
video_bind_context failed: Unable to make GL context current
Erreur de segmentation (core dumped)

**Comment by inolen** [comment]
This is probably related to some GL context changes that happened recently that I didn't quite finish, I'll try and finalize them tonight.

**Comment by inolen** [comment]
Should hopefully be resolved with 16d74604be88813fad6b6c23b6ea44d6f89883da.

**Comment by Marc34** [comment]
It works, thanks !
