### ISSUE TITLE
hw: flash memory support

### ISSUE THREAD

**Issue by inolen** [inolen/redream#11]
Save out flash memory to `~/.dreavm/dc_flash.bin` on exit. If `--flash` isn't specified on the command line, always load the flash rom from there as well.

**Comment by skmp** [comment]
Keep in mind flash is actually a state machine, and if you don't handle that some stuff breaks (haven't looked at the impl yet)

**Comment by skmp** [comment]
Looking from your code I understand you handle it as normal ram. A correct impl is pretty trivial and will save you headaches on a pretty boring part later on, take a look on https://github.com/reicast/reicast-emulator/blob/a9fc0f5aa804946ec38ee98f5b6efebe016e0e6b/core/hw/flashrom/flashrom.h#L145 :)

**Comment by inolen** [comment]
Hah, I had no idea. Cheers.

**Comment by inolen** [comment]
Closed with https://github.com/inolen/redream/commit/3bc344f8de01cc2c6b7eef1597ce7d5ca9b43a83
