### ISSUE TITLE
[Linux] please put redream config folder in  .config path

### ISSUE THREAD

**Issue by legluondunet** [inolen/redream#119]
Hello,

could you save redream config folder in  the /home/userprofilname/.config path?
It is more appropriate and standard.

Thanks.

LGDN

**Comment by inolen** [comment]
I think this being more appropriate is subjective. It seems both `~/.appname` and `~/.config/appname` are common, with the latter being a standard in freedesktop.

**Comment by gamax92** [comment]
Personally I'd also prefer if redream would place it's files in `~/.config/redream/` as well

**Comment by BPaden** [comment]
To correctly follow the standard, $XDG_CONFIG_HOME should be used, with ~/.config being the fallback.

**Comment by inolen** [comment]
Hey everyone, while I understand this may be more desirable to some people, I don't see any objective or compelling reason to support this freedesktop standard here.
