### ISSUE TITLE
Alone In The Dark Pal: video introduction all black but audio OK

### ISSUE THREAD

**Issue by legluondunet** [inolen/redream#120]
Hello,

it is no more possible to see video introduction for the game "Alone in the Dark - The New Nightmare (PAL)(FR)" with last redream version (18 july 2017):
video all black
audio OK

Terminal log:
https://pastebin.com/j910Nnnz

Thank you for your help.

Config:
Ubuntu 17.04 Zesty Zapus 64 bits - NVIDIA GeForce GTX 770 - official Ubuntu Nvidia drivers 375.66 - 1920x1080 - Processor Intel i5-3570 3,4 Ghz - 8 Go RAM

**Comment by inolen** [comment]
Fixed with e6d4aa08ad041616a3718b3531b35ba9bd1ae63e
