### ISSUE TITLE
Problems compiling on Windows Visual Studio 2015

### ISSUE THREAD

**Issue by cooperate** [inolen/redream#126]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2036	'void *': unknown size	redream	U:\redream\redream\src\guest\gdrom\disc.c	51	
Warning	C4267	'initializing': conversion from 'size_t' to 'int', possible loss of data	SDL2-static	U:\redream\redream\deps\sdl2-2.0.5\src\stdlib\SDL_qsort.c	365	
Warning	C4311	'type cast': pointer truncation from 'void *' to 'int'	SDL2-static	U:\redream\redream\deps\sdl2-2.0.5\src\stdlib\SDL_qsort.c	522	
Warning	C4996	'GetVersionExA': was declared deprecated	SDL2-static	U:\redream\redream\deps\sdl2-2.0.5\src\video\windows\SDL_windowskeyboard.c	456	
Warning	C4312	'type cast': conversion from 'unsigned int' to 'HKL' of greater size	SDL2-static	U:\redream\redream\deps\sdl2-2.0.5\src\video\windows\SDL_windowskeyboard.c	547	
Warning	C4312	'type cast': conversion from 'unsigned int' to 'HKL' of greater size	SDL2-static	U:\redream\redream\deps\sdl2-2.0.5\src\video\windows\SDL_windowskeyboard.c	582	
Warning	C4312	'type cast': conversion from 'unsigned int' to 'HKL' of greater size	SDL2-static	U:\redream\redream\deps\sdl2-2.0.5\src\video\windows\SDL_windowskeyboard.c	583	
Warning	C4312	'type cast': conversion from 'unsigned int' to 'HKL' of greater size	SDL2-static	U:\redream\redream\deps\sdl2-2.0.5\src\video\windows\SDL_windowskeyboard.c	584	
Warning	C4312	'type cast': conversion from 'unsigned int' to 'HKL' of greater size	SDL2-static	U:\redream\redream\deps\sdl2-2.0.5\src\video\windows\SDL_windowskeyboard.c	585	
Warning	C4312	'type cast': conversion from 'unsigned int' to 'HKL' of greater size	SDL2-static	U:\redream\redream\deps\sdl2-2.0.5\src\video\windows\SDL_windowskeyboard.c	586	
Error	C2220	warning treated as error - no 'object' file generated	redream	U:\redream\redream\src\guest\bios\bios.c	145	
Warning	C4101	'header': unreferenced local variable	redream	U:\redream\redream\src\guest\bios\bios.c	145	
Error	C2220	warning treated as error - no 'object' file generated	redream	U:\redream\redream\src\guest\bios\syscalls.c	302	
Warning	C4267	'initializing': conversion from 'size_t' to 'const int', possible loss of data	redream	U:\redream\redream\src\guest\bios\syscalls.c	302	
Error	C2036	'void *': unknown size	redream	U:\redream\redream\src\guest\gdrom\disc.c	73	
Error	C2133	'g2_timers': unknown size	redream	U:\redream\redream\src\guest\holly\holly.c	167	
Error	C2220	warning treated as error - no 'object' file generated	redream	U:\redream\redream\src\guest\sh4\sh4_mmu.c	21	
Warning	C4244	'initializing': conversion from '__int64' to 'int', possible loss of data	redream	U:\redream\redream\src\guest\sh4\sh4_mmu.c	21	
Error	C2220	warning treated as error - no 'object' file generated	redream	U:\redream\redream\src\emulator.c	685	
Warning	C4244	'=': conversion from 'float' to 'int', possible loss of data	redream	U:\redream\redream\src\emulator.c	685	
Warning	C4244	'=': conversion from 'float' to 'int', possible loss of data	redream	U:\redream\redream\src\emulator.c	687	
Warning	C4244	'=': conversion from 'float' to 'int', possible loss of data	redream	U:\redream\redream\src\emulator.c	690	
Warning	C4244	'=': conversion from 'float' to 'int', possible loss of data	redream	U:\redream\redream\src\emulator.c	691

**Comment by inolen** [comment]
Should be fixed with b1662457a13cd5ae18955bf30023c74cbd88ca68.
