### ISSUE TITLE
Issues running games on Windows

### ISSUE THREAD

**Issue by SonicFreak94** [inolen/redream#128]
On Windows, with every game I've tried, the game will effectively soft lock on boot and the console is filled with:

>unexpected read from 0x00000226
>unexpected write to 0x0000022e

**Comment by inolen** [comment]
What games? I tested Crazy Taxi 2 earlier when getting the build fixed, but it's always possible I broke something before actually committing the patch on my other box.

**Comment by SonicFreak94** [comment]
Sonic Adventure 1 & 2, Ecco the Dolphin, and Power Stone 1 & 2. Unfortunately I don't have Crazy Taxi 1 or 2 to test with.

**Comment by inolen** [comment]
Alright, I'll give them a try now and see what's up.

**Comment by inolen** [comment]
Should be fixed with https://github.com/inolen/redream/commit/ecca78813fb444648f3df580d8551012cfae4faf

I must have been running a debug build earlier.

**Comment by SonicFreak94** [comment]
Yep, working fine now.
