### ISSUE TITLE
popcnt not supported on intel old C2D & C2Q

### ISSUE THREAD

**Issue by 9madsheep** [inolen/redream#130]
popcnt not supported on some old intel cpus
ex. Core 2 Quad, Core 2 Duo

https://github.com/inolen/redream/blob/master/src/core/math.h

**Comment by BPaden** [comment]
I believe __builtin_popcount will fall back to a library function or something if popcnt isn't supported. The MSVC documentation suggests that their equivalent does not.

> If you run code that uses this intrinsic on hardware that does not support the popcnt instruction, the results are unpredictable.

**Comment by inolen** [comment]
That is the problem.

Need to add in a HAVE_POPCNT check to CMakeLists.txt and add fallbacks for MSVC is that is false.

**Comment by BPaden** [comment]
Might be better to check this at runtime so that you don't have to choose between Windows users with core 2s having to build themselves and people with newer cpus having degraded performance. The docs for __popcnt have info on how to do the check.

**Comment by inolen** [comment]
Doing a runtime check here would be just as slow as using the fallback I'd imagine.

Being that this isn't (at least currently) hot function, I'm fine with just always using a fallback such as http://www.hackersdelight.org/hdcodetxt/pop.c.txt.

**Comment by inolen** [comment]
Doh, while I told you the temporary fix on slack, I forgot to actually push a fix.

Fixed with https://github.com/inolen/redream/commit/f16d61a1b6bbedfbaae96a2d98300ee5dcdbb76f.

**Comment by 9madsheep** [comment]
;)
