### ISSUE TITLE
libretro core not updated anymore

### ISSUE THREAD

**Issue by bigboo3000** [inolen/redream#131]
It seems libretro core is not updated since 27/07/2017.
https://buildbot.libretro.com/nightly/windows/x86_64/latest/

Could you please compile a new version with chd support?

Thanks

**Comment by inolen** [comment]
Will do this tonight.

**Comment by inolen** [comment]
This _should_ be resolved. I see a new OSX build has been compiled correctly, it looks like Windows and Linux are still in the queue.

**Comment by inolen** [comment]
Latest is available now there.
