### ISSUE TITLE
Windows: You Initialize the App Then It Quickly Disappears

### ISSUE THREAD

**Issue by John-Enigma** [inolen/redream#136]
I wanted to try out Redream, but as you can see, everytime you try to open the emu., this happens: 
![redream initial fail](https://user-images.githubusercontent.com/22717497/29245836-39221414-7f9b-11e7-9ae0-fddbff785589.png) 
then after that, it disappears. Idk what else to do. 

I already installed the 2015 Runtime Redistributables. 

[These are the specs of desktop.](https://www.cnet.com/products/gateway-sx2110g-uw24-e1-1500-1-48-ghz-6-gb-500-gb-led-19-5/specs/)

**Comment by inolen** [comment]
Committed a fix blind with https://github.com/inolen/redream/commit/d9d8d14a6c9abd62bf0aef07d5c5888fdcc7bb05.

This should be available for download now. If it still doesn't work, I can take a look tomorrow when I'm around a Windows machine.

**Comment by John-Enigma** [comment]
Nope. It still doesn't work, for some reason. 
![screenshot 6](https://user-images.githubusercontent.com/22717497/29253958-3f5fba58-803f-11e7-983e-3aa98c50e2bf.png)

**Comment by inolen** [comment]
This just needs a better error message.

You're starting the emulator without passing it a game. If you had a real bios in place it'd drop you to the system menu, but since you don't it's asserting saying "hey, no disc".

**Comment by John-Enigma** [comment]
Hmm...

Okay. I'll try and get some BIOS as well. 

Also, is this a WIP?

**Comment by inolen** [comment]
Not sure what you mean with that question, marking this as closed for now given that the shared memory issue is resolved.

**Comment by John-Enigma** [comment]
What I meant was that if it's a WIP for redream to let you select and play via a command prompt, instead of executing Ctrl + O to find the ISO/BIN/GDI/CUE files.

**Comment by inolen** [comment]
It's a command-line driven application.

http://redream.io/docs/running

**Comment by John-Enigma** [comment]
So redream doesn't have a GUI? 

If not, are there any plans for adding GUI, like from Qt or something?

**Comment by inolen** [comment]
There's debug ui for adjusting options once inside of the emulator.

A frontend will eventually happen, but it's not the focus now.

**Comment by John-Enigma** [comment]
Got it. 

Thanks for the info sir!

**Comment by inolen** [comment]
No problem, let me know how it runs on that rig.

**Comment by John-Enigma** [comment]
Well, this is what happens now: 
![screenshot 7](https://user-images.githubusercontent.com/22717497/29254332-46834dfa-8048-11e7-9b3c-b1ecd4eeec9e.png)

**Comment by inolen** [comment]
https://github.com/inolen/redream/issues/116

That issue is high-priority for me (i'll probably do it next week) as a lot of new users hit this.

The HLE bios doesn't support booting cdis currently, only gdis.

**Comment by John-Enigma** [comment]
Um, while you're at it, do you think you can also add Dreamcast .iso, .bin, and .cue support? (Assuming that ripped Dreamcast images come in BIN and CUE formats.)

**Comment by inolen** [comment]
I'm not looking to support any more formats other than what's already supported for now (gdi, cdi and chd).

GDI being the most common format, CDI is common as well but the integrity of CDIs is _really_ hit or miss, and CHD is a compressed format created by Mame which you can easily convert your GDIs to save some space.

**Comment by John-Enigma** [comment]
Okay. 

Thanks for the reply. 

Once .cdi support is ready, i'll begin testing redream on my desktop.
