### ISSUE TITLE
[MSYS2] Linux-style path separators don't work

### ISSUE THREAD

**Issue by rz5** [inolen/redream#140]
In Windows, using the MSYS2/mingw terminal, using Linux style path separators on the ROM path will result in `fopen` returning `NULL`

```
$ ./redream.exe ../ROMs/dc/Power_Stone.gdi
audio backend created, 50 ms / 2205 frames latency
boot_load_rom loaded 'C:\Users\r5\.redream\boot.bin'
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hc  ount=857 interlace=0 vbstart=260 vbend=336
loading ../ROMs/dc/Power_Stone.gdi
gdi_parse track=1 filename='.\01.bin' fad=150 secsz=2352
gdi_parse track=2 filename='.\02.bin' fad=600 secsz=2352
gdi_parse track=3 filename='.\03.bin' fad=45150 secsz=2352
[C:\projects\redream\src\guest\gdrom\gdi.c:24] Check failed: fp must be non-NULL
```
If I write `./redream.exe ..\\ROMs\\dc\\Power_Stone.gdi` it will work as intended.

According to @inolen, this might be related to areas where the PATH_SEPARATOR variable is used.

**Comment by inolen** [comment]
https://github.com/inolen/redream/commit/e75b449944c863c3193a4dd7589ef713253bb7e8 should resolve this hopefully.

**Comment by rz5** [comment]
The issue, as described above, is indeed fixed, thanks. Closing it.
