### ISSUE TITLE
no key assignment for analogue stick

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [inolen/redream#141]
Some games need analogue input, and we can't play such games with keyboard.

**Comment by literalmente-game** [comment]
I can add that this is true for these games I've tested so far:
- Maken X
- Fighting Force 2
- Suzuki Alstare - Extreme Racing
- Time Stalkers

**Comment by mohsinous** [comment]
Is it that hard to fix this issue!!!!!?

**Comment by inolen** [comment]
This should be fixed with https://github.com/inolen/redream/commit/166bc1b717e156ab933faee22861b1e448ce1113.

The joystick keys have been split such that there is a positive / negative key for each axis, and the wasd keys have been changed to by default control the joystick instead of the dpad.

**Comment by mohsinous** [comment]
@inolen as always thank you for hard work on this amazing Redream!!!
would you some search on Cheat Engine for me that why it doesnt work on Redream!!!
i test CE on demul and nulldc and works!!!

**Comment by inolen** [comment]
I won't be looking into why Cheat Engine has issues with redream for whatever reason.

**Comment by mohsinous** [comment]
Again thanks for your great works on Redream!!!

**Comment by mohsinous** [comment]
@inolen Would you check issue #197 plz?
