### ISSUE TITLE
Resident Evil: Code Veronica runs too fast

### ISSUE THREAD

**Issue by Shoegzer** [inolen/redream#142]
Game speed is off.  You can tell right from the main menu - if you try navigating through the menu options it jumps from the top option immediately to the bottom one.  Speed issues are also noticeable in-game and in the cutscenes.

**Comment by bigboo3000** [comment]
I just tested it and this game is working fine, I think you can close this issue.

**Comment by Shoegzer** [comment]
I just re-tested it, and the game is not working fine - the speed issues with this game are still there.  This issue will be kept open. 

I should note that YMMV based on OS, graphics drivers etc.  The test machine I used was a Linux Mint 18 x64 system with 4.11 kernel, with Nvidia 860M and 375.66 drivers.

**Comment by mohsinous** [comment]
i have this problem too!!! also game has some 2D texture glitches too.

**Comment by mohsinous** [comment]
this is the video that shows the problem

![2017-10-12_10-57-31](https://user-images.githubusercontent.com/32609205/31484375-f3d168de-af3c-11e7-9e95-6d4914079f28.gif)

**Comment by mohsinous** [comment]
and this is 2D glitches and claire running tooo fast!! (regina in dino crisis is another example)

![2017-10-12_11-12-38](https://user-images.githubusercontent.com/32609205/31484953-0dfbc482-af3f-11e7-8af2-ed859541918e.gif)

**Comment by bigboo3000** [comment]
what version of code veronica are you using? USA?
in .cdi or .gdi format?

**Comment by bigboo3000** [comment]
OK i can confirm the problem on my system with both USA and Europe (PAL 50hz only) versions.

The only version that works fine is the hacked PAL60 version from "japanese-cake" on his livejournal site.
That's the one I tried first so I didn't catch this bug.

**Comment by mohsinous** [comment]
i just retest RE:CV and confirm the menu navigation problem is fixed but 2D glitch is there yet ):

**Comment by inolen** [comment]
Interesting, the RE:CV menu speed issue was inadvertently fixed by setting the correct interlace field each frame:
https://github.com/inolen/redream/blob/master/src/guest/pvr/pvr.c#L189

This landed when I added support for raw framebuffer writes with:
https://github.com/inolen/redream/commit/046411f8f82fa3076ff55f2c5c38dad2e92838b9

The purpose of which, was to fix several homebrew demos (as well as the SEGA license screen code) which write directly to the framebuffer.
