### ISSUE TITLE
Feature request: NAOMI / NAOMI2 / Atomiswave support

### ISSUE THREAD

**Issue by Shoegzer** [inolen/redream#145]
This would instantly add tons of new (arcade) games to Redream's compatibility as the hardware is so similar to the Dreamcast.  Other emulators (nullDC, Demul) support this hardware too, so hopefully it wouldn't be too difficult to add.  It also helps that Redream already supports the MAME CHD archival format as it's instantly compatible with MAME images.

**Comment by inolen** [comment]
Going to close this for now just since this is so far off from being a priority. I'm sure one day it will happen, but it will be a long while.
