### ISSUE TITLE
(Libretro) Save directory?

### ISSUE THREAD

**Issue by orbea** [inolen/redream#146]
Where does redream store its saves when using the libretro core? I have not been able to figure this out by exploring the documentation, searching my file system or examining the output of strace.

I configure RetroArch to put its saves in a new directory for every core so I should expect to find saves in a place like `~/games/roms/.saves/retroarch/redream/`, but that directory remains unused. I have not found saves in the content directory or `$PWD` either. What am I missing?

**Comment by inolen** [comment]
All files are written out to the application directory:

https://github.com/inolen/redream/blob/master/src/host/retro_host.c#L212
https://github.com/inolen/redream/blob/master/src/host/sdl_host.c#L802

**Comment by orbea** [comment]
For other people reading this, the saves are in the System/Bios directory with the names: `vmu_%d_%d.bin`. Thanks for the help!
