### ISSUE TITLE
Build fails with GCC 7

### ISSUE THREAD

**Issue by rdanbrook** [inolen/redream#148]
`/home/user/src/redream/src/guest/gdrom/disc.c: In function ‘disc_create’:
/home/user/src/redream/src/guest/gdrom/disc.c:247:52: error: ‘%s’ directive output may be truncated writing up to 11 bytes into a region of size between 8 and 158 [-Werror=format-truncation=]
   snprintf(disc->uid, sizeof(disc->uid), "%s %s %s %s", disc->product_name,
                                                    ^~
/home/user/src/redream/src/guest/gdrom/disc.c:247:3: note: ‘snprintf’ output between 4 and 165 bytes into a destination of size 161
   snprintf(disc->uid, sizeof(disc->uid), "%s %s %s %s", disc->product_name,
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            disc->product_number, disc->product_version, disc->media_config);
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
`

**Comment by inolen** [comment]
Should be fixed with https://github.com/inolen/redream/commit/f2b2639dd273648bbb8a10cea670e640ef17ffa7.

**Comment by rdanbrook** [comment]
Yep, that does it. Thanks.
