### ISSUE TITLE
Chu-Chu Rocket (Europe) - random crash when selecting frequency

### ISSUE THREAD

**Issue by bigboo3000** [inolen/redream#152]
If you choose 50Hz on the frequency selection screen it works.
But if you choose 60Hz it crashes:
[C:\projects\redream\src\guest\pvr\ta.c:862] Check failed: ctx must be non-NULL

**Comment by bigboo3000** [comment]
fixed with correct bios

**Comment by bigboo3000** [comment]
My bad in fact it works in retroarch, but the problem is still there in standalone.

**Comment by bigboo3000** [comment]
It works fine with HLE BIOS but crash with real BIOS.

**Comment by inolen** [comment]
Good to know, as usual, thanks for the continued reports, excited to take a look in the next week or so.

**Comment by bigboo3000** [comment]
same problem with shenmue II (europe).
If you change broadcast to pal, a tv setting appears at boot and when you select a frenquency it crashes with almost the same error
[C:\projects\redream\src\guest\pvr\ta.c:861] Check failed: ctx must be non-NULL

with default ntsc setting this tv mode select screen doesn't appear so there is no bug.

**Comment by bigboo3000** [comment]
I just checked this game again.
The error when crashing is now [C:\projects\redream\src\guest\pvr\ta.c:837] Check failed: ctx must be non-NULL.

But in fact it doesn't depend on what frequency you choose (50 or 60hz), it just happens randomly.
One time you start the game and select a frequency and it works fine, the next time it crash and so on.

**Comment by inolen** [comment]
This should be fixed with https://github.com/inolen/redream/commit/a23a145a60cc376de35b3d8085d944298696f969.

**Comment by bigboo3000** [comment]
It's fixed thanks

**Comment by cjslava** [comment]
The most recent Linux 64bit binaries have the same issue.  Was this fixed across the board?
