### ISSUE TITLE
Millennium Racer Y2K (Unreleased) doesn't load

### ISSUE THREAD

**Issue by bigboo3000** [inolen/redream#155]
There is a copy of this unreleased game in .gdi format, I tried it (converted in chd v5 format) but it doesn't work.
It works correctly in DEMUL.

dc_load path=D:\Emulation\Archives\consoles_discs\dreamcast\Millennium Racer Y2K (Unreleased).chd
chd_parse 'TRACK:1 TYPE:MODE1 SUBTYPE:NONE FRAMES:658 PAD:150 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=1 fad=150 secsz=2048
chd_parse 'TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:44342 PAD:43816 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=2 fad=808 secsz=2352
chd_parse 'TRACK:3 TYPE:MODE1 SUBTYPE:NONE FRAMES:306526 PAD:150 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=3 fad=45150 secsz=2048
chd_parse 'TRACK:4 TYPE:AUDIO SUBTYPE:NONE FRAMES:3829 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=4 fad=351676 secsz=2352
chd_parse 'TRACK:5 TYPE:AUDIO SUBTYPE:NONE FRAMES:25616 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=5 fad=355505 secsz=2352
chd_parse 'TRACK:6 TYPE:AUDIO SUBTYPE:NONE FRAMES:3682 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=6 fad=381121 secsz=2352
chd_parse 'TRACK:7 TYPE:AUDIO SUBTYPE:NONE FRAMES:29750 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=7 fad=384803 secsz=2352
chd_parse 'TRACK:8 TYPE:AUDIO SUBTYPE:NONE FRAMES:51670 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=8 fad=414553 secsz=2352
chd_parse 'TRACK:9 TYPE:AUDIO SUBTYPE:NONE FRAMES:18077 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=9 fad=466223 secsz=2352
chd_parse 'TRACK:10 TYPE:AUDIO SUBTYPE:NONE FRAMES:22626 PAD:150 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=10 fad=484300 secsz=2352
chd_parse 'TRACK:11 TYPE:MODE1 SUBTYPE:NONE FRAMES:42374 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=11 fad=506926 secsz=2048
[C:\projects\redream\src\guest\gdrom\disc.c:104] Check failed: pvd->type == 1

**Comment by bigboo3000** [comment]
With the latest version the problem is now different, it goes back to bios menu

pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
bios_override_settings region=usa lang=english bcast=ntsc
audio_create_device latency=50 ms/2205 frames
imgui_update_font_tex w=512 h=64
dc_load path=D:\Emulation\Archives\consoles_discs\dreamcast\Millennium Racer Y2K (Unreleased).chd
chd_parse 'TRACK:1 TYPE:MODE1 SUBTYPE:NONE FRAMES:658 PAD:150 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=1 fad=150 secsz=2048
chd_parse 'TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:44342 PAD:43816 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=2 fad=808 secsz=2352
chd_parse 'TRACK:3 TYPE:MODE1 SUBTYPE:NONE FRAMES:306526 PAD:150 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=3 fad=45150 secsz=2048
chd_parse 'TRACK:4 TYPE:AUDIO SUBTYPE:NONE FRAMES:3829 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=4 fad=351676 secsz=2352
chd_parse 'TRACK:5 TYPE:AUDIO SUBTYPE:NONE FRAMES:25616 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=5 fad=355505 secsz=2352
chd_parse 'TRACK:6 TYPE:AUDIO SUBTYPE:NONE FRAMES:3682 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=6 fad=381121 secsz=2352
chd_parse 'TRACK:7 TYPE:AUDIO SUBTYPE:NONE FRAMES:29750 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=7 fad=384803 secsz=2352
chd_parse 'TRACK:8 TYPE:AUDIO SUBTYPE:NONE FRAMES:51670 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=8 fad=414553 secsz=2352
chd_parse 'TRACK:9 TYPE:AUDIO SUBTYPE:NONE FRAMES:18077 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=9 fad=466223 secsz=2352
chd_parse 'TRACK:10 TYPE:AUDIO SUBTYPE:NONE FRAMES:22626 PAD:150 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=10 fad=484300 secsz=2352
chd_parse 'TRACK:11 TYPE:MODE1 SUBTYPE:NONE FRAMES:42374 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=11 fad=506926 secsz=2048
disc_create id= - Y2K FIGHTERS                                                                                                 TOC1^░ 20010330     0799A10
sh4_ccn_reset
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=260 vbend=336
arm7_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
arm7_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
arm7_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36

**Comment by inolen** [comment]
It may be worth retesting this after the gdrom changes.

**Comment by bigboo3000** [comment]
It still doesn' work after https://github.com/inolen/redream/commit/223b3a5d9a398ce438592c4af3027d860f2bb320

**Comment by bigboo3000** [comment]
when using hle bios the problem is the same as before:

pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
bios_override_settings region=usa lang=french bcast=ntsc time=0x7fac0db0
audio_create_device latency=92 ms/4096 frames
imgui_update_font_tex w=512 h=64
dc_load path= \Millennium Racer Y2K (Unreleased).chd
chd_parse 'TRACK:1 TYPE:MODE1 SUBTYPE:NONE FRAMES:658 PAD:150 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=1 fad=150 secsz=2048
chd_parse 'TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:44342 PAD:43816 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=2 fad=808 secsz=2352
chd_parse 'TRACK:3 TYPE:MODE1 SUBTYPE:NONE FRAMES:306526 PAD:150 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=3 fad=45150 secsz=2048
chd_parse 'TRACK:4 TYPE:AUDIO SUBTYPE:NONE FRAMES:3829 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=4 fad=351676 secsz=2352
chd_parse 'TRACK:5 TYPE:AUDIO SUBTYPE:NONE FRAMES:25616 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=5 fad=355505 secsz=2352
chd_parse 'TRACK:6 TYPE:AUDIO SUBTYPE:NONE FRAMES:3682 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=6 fad=381121 secsz=2352
chd_parse 'TRACK:7 TYPE:AUDIO SUBTYPE:NONE FRAMES:29750 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=7 fad=384803 secsz=2352
chd_parse 'TRACK:8 TYPE:AUDIO SUBTYPE:NONE FRAMES:51670 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=8 fad=414553 secsz=2352
chd_parse 'TRACK:9 TYPE:AUDIO SUBTYPE:NONE FRAMES:18077 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=9 fad=466223 secsz=2352
chd_parse 'TRACK:10 TYPE:AUDIO SUBTYPE:NONE FRAMES:22626 PAD:150 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=10 fad=484300 secsz=2352
chd_parse 'TRACK:11 TYPE:MODE1 SUBTYPE:NONE FRAMES:42374 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=11 fad=506926 secsz=2048
disc_create id= - Y2K FIGHTERS                                                                                                 TOC1^░ 20010330     0799A10
bios_boot using hle bootstrap
[C:\projects\redream\src\guest\gdrom\disc.c:129] Check failed: pvd->type == 1

**Comment by inolen** [comment]
Fixed loading the GDI of this with 202c172759a23c27f7eee1c21970395997a71dd7.

**Comment by inolen** [comment]
Hopefully your CHD issue is resolved with 00e5376562e082bf63bfe4c081bdf00d0e844bb3.

**Comment by bigboo3000** [comment]
It works now, thanks.
For the record it keeps repeating this in the log:
mem_unhandled_read addr=0x103ff4a0
mem_unhandled_read addr=0x103ff498
mem_unhandled_read addr=0x103ff4a0
mem_unhandled_read addr=0x103ff498
mem_unhandled_read addr=0x103ff4a0
mem_unhandled_read addr=0x103ff498
mem_unhandled_read addr=0x103ff4a0
mem_unhandled_read addr=0x103ff498
mem_unhandled_read addr=0x103ff4a0
