### ISSUE TITLE
Remove version numbers from directory names

### ISSUE THREAD

**Issue by vgturtle127** [inolen/redream#16]
I would recommend that for the future, we remove the version numbers from the directory names. That way. if we upgrade the dependencies, it won't be confusing. Also, it won't be as difficult to upgrade dependencies and also have to change the directory names.

If we want version numbers to be somewhere, you could create a VERSIONS.md file in the deps directory and have all the versions there. I can do this via a pull request, if you would like.

This might also be a good time to update all the dependencies as well (while the project is somewhat small).

Here are the versions we have, and the newest versions available:

Eigen 3.2.1 - newest is 3.2.7
gflags 2.1.2 - newest is 2.1.2 (no upgrade necessary)
glew 1.13 - newest is 1.13 (no upgrade necessary)
gtest 1.7.0 - newest is 1.7.0 (no upgrade necessary)
json11 - upgrade to newest commit available here: https://github.com/dropbox/json11
microprofile - upgrade to either latest original version (https://bitbucket.org/jonasmeyer/microprofile)
or upgrade to the fork that is here: (https://github.com/zeux/microprofile)
SDL 2.0.3 - upgrade to SDL 2.0.4
stb_truetype 1.05 - upgrade to 1.09 here (https://github.com/nothings/stb/blob/master/stb_truetype.h)
Xbyak 4.85 - upgrade to Xbyak 4.90

Anyway, I hope this helps.

**Comment by inolen** [comment]
While I should definitely update these dependencies soon, I'll probably keep the version numbers directly in the folder names.

By stripping the version number from where it's relevant and shuffling it off to an inconsequential metadata file, it becomes "out of sight, out of mind" I feel.

**Comment by vgturtle127** [comment]
@inolen Agreed on both accounts. :smile:
