### ISSUE TITLE
hle bios: San Francisco RUSH 2049 doesn't work

### ISSUE THREAD

**Issue by bigboo3000** [inolen/redream#161]
with real BIOS it goes back to bios menu
with HLE BIOS it loads correctly but image is very zoomed

**Comment by bigboo3000** [comment]
I tried the latest version but with the real bios it still doesn't load (go back to main menu).
I'm using this bios:
sha1: 8951d1bb219ab2ff8583033d2119c899cc81f18c

**Comment by inolen** [comment]
@bigboo3000 ah, just realized this was for the PAL version.

I will have to get a hold of that to test.

**Comment by bigboo3000** [comment]
I checked again and the PAL version works too.
But you need to change BOTH settings in redream:
region to europe AND broadcast to PAL

**Comment by inolen** [comment]
Hmph, by default games are patched to work in all regions, so setting the region doesn't seem like it should be required. I never test PAL games, perhaps the bios does some additional sanity checks based on the broadcast setting on them.

**Comment by bigboo3000** [comment]
It's the only PAL game with this problem (I tested 50 PAL games all with default usa and ntsc settings)

**Comment by bigboo3000** [comment]
the USA version also goes back to bios menu when region is set to europe.
So it's a check in the game.

**Comment by inolen** [comment]
Ah, good detective work!

I think we can close this now then.

**Comment by bigboo3000** [comment]
the problem with hle bios is still there

**Comment by inolen** [comment]
Doh, forgot about that.

**Comment by bigboo3000** [comment]
btw hle bios is not working anymore with any game with latest redream version on my machine.

**Comment by inolen** [comment]
Oops, the Samba De Amigo fix broke that, will push a fix tomorrow.

**Comment by bigboo3000** [comment]
With HLE bios on the PAL version only the top left of the screen is diplayed, like it is zoomed:
![sf2049](https://user-images.githubusercontent.com/16479698/31861873-fe6538f2-b734-11e7-9708-cb52a6a7bffa.png)

**Comment by bigboo3000** [comment]
with latest redream version the display is not zoomed anymore but there is still a problem with controller, I close this and comment in https://github.com/inolen/redream/issues/150
