### ISSUE TITLE
Metropolis Street Racer (Europe) crash

### ISSUE THREAD

**Issue by bigboo3000** [inolen/redream#168]
crash after video intro

(...)
sh4_mmu_utlb_sync memory mapping not supported
sh4_mmu_utlb_sync memory mapping not supported
sh4_mmu_utlb_sync memory mapping not supported
sh4_mmu_utlb_sync memory mapping not supported
sh4_mmu_utlb_sync memory mapping not supported
sh4_mmu_utlb_sync memory mapping not supported
sh4_mmu_utlb_sync memory mapping not supported
sh4_mmu_utlb_sync memory mapping not supported
sh4_mmu_utlb_sync memory mapping not supported
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
arm7_reset
unexpected read from 0x0000079c
unexpected read from 0x000007a0
unexpected read from 0x000007a4
unexpected read from 0x000007a8
unexpected read from 0x000007ac
unexpected read from 0x000007b0
unexpected read from 0x000007b4
unexpected read from 0x000007b8
unexpected read from 0x000007bc
unexpected read from 0x000007c0
unexpected read from 0x000007c4
unexpected read from 0x000007c8
unexpected read from 0x000007cc
unexpected read from 0x000007d0
unexpected read from 0x000007d4
unexpected read from 0x000007d8
unexpected read from 0x000007dc
unexpected read from 0x000007e0
unexpected read from 0x000007e4
unexpected read from 0x000007e8
unexpected read from 0x000007ec
unexpected read from 0x000007f0
unexpected read from 0x000007f4
unexpected read from 0x000007f8
unexpected read from 0x000007fc
unexpected read from 0x00000800
unexpected read from 0x00000804
unexpected read from 0x00000808
unexpected read from 0x0000080c
unexpected read from 0x00000810
unexpected read from 0x00000814
unexpected read from 0x00000818
unexpected read from 0x0000081c
unexpected read from 0x00000820
unexpected read from 0x00000824
unexpected read from 0x000007a8
unexpected read from 0x000007ac
[C:\projects\redream\src\guest\pvr\tex.c:679] Check failed: !compressed

**Comment by inolen** [comment]
While I don't get this assert on latest (USA version) rendering is completely fubar after the intro movies.

It appears to be a SH4 bug, bad vertex data is being passed to the ta.

**Comment by inolen** [comment]
Scary stuff, but it looks like the graphical corruption is caused by a gdrom refactor e3e7975a6cdfe78e8a640b29ddd8bcfad9c95e7e.

I have a feeling this bled over to other games as well.

**Comment by inolen** [comment]
The USA version of this renders / runs fine for me with 223b3a5d9a398ce438592c4af3027d860f2bb320.

**Comment by bigboo3000** [comment]
Pal version fixed too, I close this issue
