### ISSUE TITLE
2D graphic corruption : Cyber Troopers Virtual On - Oratorio Tangram (USA)

### ISSUE THREAD

**Issue by bigboo3000** [inolen/redream#170]
ingame:

![virtualon](https://user-images.githubusercontent.com/16479698/30482042-c466bcc8-9a21-11e7-882b-4137999d0c6d.png)

**Comment by inolen** [comment]
This appears to also be fixed with https://github.com/inolen/redream/commit/5280bf813dfe28547fd96a2ea002e8343a7f4d89.
