### ISSUE TITLE
Xcode compiled redream does not play intro video in Sonic Adventure

### ISSUE THREAD

**Issue by duckey77** [inolen/redream#174]
Intro video is not played on Sonic Adventures at start-up on Xcode compiled redream.  Cut scenes display the same dialog text every time dialog should be placed on the screen.

Makefile compiled redream plays the intro video and displayed text correctly in cut scenes.

both projects are build with the instructions:
http://redream.io/docs/building

cmake version 3.6.1
xcode Version 8.3.3 (8E3004b)

macOS 12.6.2 
MacBook Pro (Retina, 15-inch, Mid 2014)
Intel Iris Pro 1536 MB
redeem git source 5feae48f5fec62d1c1535b75024dad05c034734b

**Comment by inolen** [comment]
My guess here is that you're building a debug executable.

Texture caching is disabled in debug builds for the same reason that fastmem is:
https://github.com/inolen/redream/blob/master/src/jit/jit.c#L199

**Comment by duckey77** [comment]
Wow, that was fast.  let me rebuild with that knowledge

**Comment by duckey77** [comment]
Yep that was it.   Thank you for the clarification

**Comment by inolen** [comment]
No problem.
