### ISSUE TITLE
Dynamite Cop (USA) Letters slightly cut off

### ISSUE THREAD

**Issue by kurayami6** [inolen/redream#175]
Letters are slightly cut off on the memory card screen.

![dynamite cop usa -170917-114327](https://user-images.githubusercontent.com/31968468/30517326-17c17e7a-9b9f-11e7-8c69-565ce29d87bd.png)

For comparison, what it should look like.

![maxresdefault](https://user-images.githubusercontent.com/31968468/30517330-2c206d68-9b9f-11e7-832a-22e92adae249.jpg)

**Comment by inolen** [comment]
I believe this was an issue with the widescreen patch for Dynamite Cop. I've since disabled that code due to problems like this, and it appears to render correctly for me.
