### ISSUE TITLE
[CHD] pvd->type == 1 assertion fails

### ISSUE THREAD

**Issue by alondero** [inolen/redream#176]
I've recently started converting my Dreamcast games into CHD format, but notice that this seems to be breaking the Redream Retroarch core
I'm getting the following error:

S:\Emulators\RetroArch>[INFO] RetroArch 1.6.7 (Git 557c6c1)
[INFO] Redirecting save file to "S:\Media\Sega Dreamcast\Games\Roadsters (USA).srm".
[INFO] Redirecting savestate to "S:\Media\Sega Dreamcast\Games\Roadsters (USA).state".
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES
Built: Sep 12 2017
[INFO] Version: 1.6.7
[INFO] Git: 557c6c1
[INFO] =================================================
[INFO] [Config]: Loading default config.
[INFO] [Config]: loading config from: (null).
[WARN] Key name / not found.
[INFO] Loading dynamic libretro core from: "S:\Emulators\RetroArch\cores\redream_libretro.dll"
[INFO] [overrides] core-specific overrides found at S:\Emulators\RetroArch\config\redream\redream.cfg.
[INFO] [overrides] no game-specific overrides found at S:\Emulators\RetroArch\config\redream\Roadsters (USA).cfg.
[INFO] Config: appending config "S:\Emulators\RetroArch\config\redream\redream.cfg"
[WARN] Key name / not found.
[INFO] Shaders: preset directory: S:\Emulators\RetroArch\shaders\presets
[INFO] Shaders: no game-specific preset found at S:\Emulators\RetroArch\shaders\presets\redream\Roadsters (USA).cgp.
[INFO] Shaders: no game-specific preset found at S:\Emulators\RetroArch\shaders\presets\redream\Roadsters (USA).glslp.
[INFO] Shaders: no core-specific preset found at S:\Emulators\RetroArch\shaders\presets\redream\redream.cgp.
[INFO] Shaders: no core-specific preset found at S:\Emulators\RetroArch\shaders\presets\redream\redream.glslp.
[INFO] Remaps: remap directory: S:\Emulators\RetroArch\config\remaps
[INFO] Remaps: no game-specific remap found at S:\Emulators\RetroArch\config\remaps\redream\Roadsters (USA).rmp.
[INFO] Remaps: no core-specific remap found at S:\Emulators\RetroArch\config\remaps\redream\redream.rmp.
[INFO] Redirecting save file to "C:\Users\XXXXXX\Google Drive\Apps\Emulation\Sega Dreamcast\Saves\Roadsters (USA).srm".
[INFO] Redirecting savestate to "C:\Users\XXXXXX\Google Drive\Apps\Emulation\Sega Dreamcast\Save States\Roadsters (USA).state".
[INFO] Environ SYSTEM_DIRECTORY: "S:\Emulators\RetroArch\system".
[INFO] Content loading skipped. Implementation will load it on its own.
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO]  RetroPad, User 1, Button "B (bottom)" => "A"
[INFO]  RetroPad, User 1, Button "Y (left)" => "X"
[INFO]  RetroPad, User 1, Button "Start" => "Start"
[INFO]  RetroPad, User 1, Button "D-Pad Up" => "D-Pad Up"
[INFO]  RetroPad, User 1, Button "D-Pad Down" => "D-Pad Down"
[INFO]  RetroPad, User 1, Button "D-Pad Left" => "D-Pad Left"
[INFO]  RetroPad, User 1, Button "D-Pad Right" => "D-Pad Right"
[INFO]  RetroPad, User 1, Button "A (right)" => "B"
[INFO]  RetroPad, User 1, Button "X (up)" => "Y"
[INFO]  RetroPad, User 1, Button "L2" => "L"
[INFO]  RetroPad, User 1, Button "R2" => "R"
[INFO]  RetroPad, User 2, Button "B (bottom)" => "A"
[INFO]  RetroPad, User 2, Button "Y (left)" => "X"
[INFO]  RetroPad, User 2, Button "Start" => "Start"
[INFO]  RetroPad, User 2, Button "D-Pad Up" => "D-Pad Up"
[INFO]  RetroPad, User 2, Button "D-Pad Down" => "D-Pad Down"
[INFO]  RetroPad, User 2, Button "D-Pad Left" => "D-Pad Left"
[INFO]  RetroPad, User 2, Button "D-Pad Right" => "D-Pad Right"
[INFO]  RetroPad, User 2, Button "A (right)" => "B"
[INFO]  RetroPad, User 2, Button "X (up)" => "Y"
[INFO]  RetroPad, User 2, Button "L2" => "L"
[INFO]  RetroPad, User 2, Button "R2" => "R"
[INFO]  RetroPad, User 3, Button "B (bottom)" => "A"
[INFO]  RetroPad, User 3, Button "Y (left)" => "X"
[INFO]  RetroPad, User 3, Button "Start" => "Start"
[INFO]  RetroPad, User 3, Button "D-Pad Up" => "D-Pad Up"
[INFO]  RetroPad, User 3, Button "D-Pad Down" => "D-Pad Down"
[INFO]  RetroPad, User 3, Button "D-Pad Left" => "D-Pad Left"
[INFO]  RetroPad, User 3, Button "D-Pad Right" => "D-Pad Right"
[INFO]  RetroPad, User 3, Button "A (right)" => "B"
[INFO]  RetroPad, User 3, Button "X (up)" => "Y"
[INFO]  RetroPad, User 3, Button "L2" => "L"
[INFO]  RetroPad, User 3, Button "R2" => "R"
[INFO]  RetroPad, User 4, Button "B (bottom)" => "A"
[INFO]  RetroPad, User 4, Button "Y (left)" => "X"
[INFO]  RetroPad, User 4, Button "Start" => "Start"
[INFO]  RetroPad, User 4, Button "D-Pad Up" => "D-Pad Up"
[INFO]  RetroPad, User 4, Button "D-Pad Down" => "D-Pad Down"
[INFO]  RetroPad, User 4, Button "D-Pad Left" => "D-Pad Left"
[INFO]  RetroPad, User 4, Button "D-Pad Right" => "D-Pad Right"
[INFO]  RetroPad, User 4, Button "A (right)" => "B"
[INFO]  RetroPad, User 4, Button "X (up)" => "Y"
[INFO]  RetroPad, User 4, Button "L2" => "L"
[INFO]  RetroPad, User 4, Button "R2" => "R"
[INFO] Environ SET_HW_RENDER.
[INFO] Requesting core OpenGL context (3.3).
boot_load_rom loaded 'S:\Emulators\RetroArch\system\dc\boot.bin'
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
dc_load path=S:\Media\Sega Dreamcast\Games\Roadsters (USA).chd
chd_parse 'TRACK:1 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:754 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=1 fad=150 secsz=2352
chd_parse 'TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:44246 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=2 fad=904 secsz=2352
chd_parse 'TRACK:3 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:302326 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=3 fad=45150 secsz=2352
chd_parse 'TRACK:4 TYPE:AUDIO SUBTYPE:NONE FRAMES:10808 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=4 fad=347476 secsz=2352
chd_parse 'TRACK:5 TYPE:AUDIO SUBTYPE:NONE FRAMES:8261 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=5 fad=358284 secsz=2352
chd_parse 'TRACK:6 TYPE:AUDIO SUBTYPE:NONE FRAMES:16052 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=6 fad=366545 secsz=2352
chd_parse 'TRACK:7 TYPE:AUDIO SUBTYPE:NONE FRAMES:15444 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=7 fad=382597 secsz=2352
chd_parse 'TRACK:8 TYPE:AUDIO SUBTYPE:NONE FRAMES:14742 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=8 fad=398041 secsz=2352
chd_parse 'TRACK:9 TYPE:AUDIO SUBTYPE:NONE FRAMES:15897 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=9 fad=412783 secsz=2352
chd_parse 'TRACK:10 TYPE:AUDIO SUBTYPE:NONE FRAMES:15457 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=10 fad=428680 secsz=2352
chd_parse 'TRACK:11 TYPE:AUDIO SUBTYPE:NONE FRAMES:17268 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=11 fad=444137 secsz=2352
chd_parse 'TRACK:12 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:87895 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=12 fad=461405 secsz=2352
[src/guest/gdrom/disc.c:104] Check failed: pvd->type == 1

**Comment by inolen** [comment]
Is this the only game the error occurs on?

**Comment by alondero** [comment]
No I've tried with a few others too. Same issue.

**Comment by inolen** [comment]
Perhaps a better question is - do any CHDs work for you?

**Comment by alondero** [comment]
Yeah, I've not got that many games but none of my newly made CHDs work, even though the GDI works. I'm using chdman with the -createcd option. 
I've tried:
Daytona USA
Roadsters
Flag to Flag
San Francisco Rush 2049
Crazy Taxi

This on using the latest core and Retroarch build from the buildbot

**Comment by inolen** [comment]
Just tested with Daytona USA on the standalone and it worked, log looks like:

```
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
dc_load path=/home/inolen/daytona.chd
chd_parse 'TRACK:1 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:450 PAD:150 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=1 fad=150 secsz=2352
chd_parse 'TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:44550 PAD:44024 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=2 fad=600 secsz=2352
chd_parse 'TRACK:3 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:504150 PAD:0 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0' track=3 fad=45150 secsz=2352
disc_create id=DAYTONAUSA MK-51037 V1.004 GD-ROM1/1 bootfile=1ST_READ.BIN fad=548168 len=2010720
```

**Comment by bigboo3000** [comment]
@alondero what version of chdman are you using?
only version after 0.176 are fine for 100% lossless compression.

**Comment by alondero** [comment]
Thank you @bigboo3000! That was the problem - was using chdman from a really old version of MAME. Just tested with a newly created CHD and it works! I'll close this
