### ISSUE TITLE
linux : GDI wont run? Goes straight to bios screen

### ISSUE THREAD

**Issue by 7oxicshadow** [inolen/redream#177]
I have just build the latest master and none of my games will boot (GDI). The game is recognised as the following is shown in terminal:

> dc_load path=/mnt/games/native_emulators/reicast/roms/ep1_racer/game.gdi
> gdi_parse track=1 filename='/mnt/games/native_emulators/reicast/roms/ep1_racer/track01.bin' fad=150 secsz=2352
> gdi_parse track=2 filename='/mnt/games/native_emulators/reicast/roms/ep1_racer/track02.raw' fad=903 secsz=2352
> gdi_parse track=3 filename='/mnt/games/native_emulators/reicast/roms/ep1_racer/track03.bin' fad=45150 secsz=2352
> gdi_parse track=4 filename='/mnt/games/native_emulators/reicast/roms/ep1_racer/track04.raw' fad=356604 secsz=2352
> gdi_parse track=5 filename='/mnt/games/native_emulators/reicast/roms/ep1_racer/track05.bin' fad=357205 secsz=2352
> disc_create id=STAR WARS EPISODE 1 RACER T23001N V1.001 GD-ROM1/1

If i select the bouncing DC controller in the bios screen it says "Please insert game disc."

**Comment by inolen** [comment]
I think this might be related to how I updated the region patching / handled existing region settings.

Previously, the default setting for `--region` was `auto`, but that setting is so longer available.

Could you try running with `--region=usa` and see if it makes things work.

**Comment by 7oxicshadow** [comment]
As you suspected it made no difference

full log (ignore my debug):

>!!!!!!!!!! got : /mnt/games/native_emulators/reicast/roms/ep1_racer/game.gdi
> boot_load_rom loaded '/home/toxicshadow/.redream/boot.bin'
> !!!!!!!!!!!!!GDROM SET DISC
> !!!!!!!!!!FAIL
> pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
> bios_override_settings region=usa lang=english bcast=ntsc
> audio_init latency=50 ms/2205 frames
> input_controller_added port=0 name=X360 Wireless Controller
> dc_load path=/mnt/games/native_emulators/reicast/roms/ep1_racer/game.gdi
> gdi_parse track=1 filename='/mnt/games/native_emulators/reicast/roms/ep1_racer/track01.bin' fad=150 secsz=2352
> gdi_parse track=2 filename='/mnt/games/native_emulators/reicast/roms/ep1_racer/track02.raw' fad=903 secsz=2352
> gdi_parse track=3 filename='/mnt/games/native_emulators/reicast/roms/ep1_racer/track03.bin' fad=45150 secsz=2352
> gdi_parse track=4 filename='/mnt/games/native_emulators/reicast/roms/ep1_racer/track04.raw' fad=356604 secsz=2352
> gdi_parse track=5 filename='/mnt/games/native_emulators/reicast/roms/ep1_racer/track05.bin' fad=357205 secsz=2352
> disc_create id=STAR WARS EPISODE 1 RACER T23001N V1.001 GD-ROM1/1
> !!!!!!!!!!!!!GDROM SET DISC
> input_controller_added port=1 name=X360 Wireless Controller
> sh4_ccn_reset
> pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
> pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=260 vbend=336
> arm7_reset
> sh4_ccn_reset
> sh4_ccn_reset
> sh4_ccn_reset
> pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
> pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
> pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
> pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
> pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
> arm7_reset
> pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
> sh4_ccn_reset
> sh4_ccn_reset
> sh4_ccn_reset
> sh4_ccn_reset
> pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
> pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
> pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
> pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
> pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
> arm7_reset
> pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36

**Comment by inolen** [comment]
Looks like I can repro this with SW EP1 (I was just testing Sonic Adventure when I made that change which works).

Will take a look now.

**Comment by inolen** [comment]
Fixed with https://github.com/inolen/redream/commit/46e94bc50fab2f943301aa1783baba4e3a29899a.

Sorry about that, the code was just blatantly broken while cleaning up to commit.

**Comment by inolen** [comment]
Going to close this as I'm fairly sure it resolves the issue, let me know if it's still broken.
