### ISSUE TITLE
Gamepad Problem

### ISSUE THREAD

**Issue by mohsinous** [inolen/redream#180]
I install my mi controller via scpdriver and spoof it as x360 gamepad but redream doesnt recognize it. the controller is verified to work with any steam games!!

**Comment by inolen** [comment]
What controller is it? redream used SDL's gamepad API.

**Comment by mohsinous** [comment]
Xiaomi Mi Gamepad! it doesnt work at all! by the way redream does not use analog stick!? because just dpad is shown in controller settings.

**Comment by bigboo3000** [comment]
My 8BITDO Nes 30 pro in Xinput mode (XBOX360 pad mapping) is not recognized either.

**Comment by inolen** [comment]
@bigboo3000 odd, that controller shows up in the SDL gamecontrollerdb:
https://github.com/inolen/redream/blob/master/deps/sdl2/src/joystick/SDL_gamecontrollerdb.h#L38

Perhaps it's a situation where you don't have the xinput / dinput headers, so SDL_JOYSTICK_XINPUT / SDL_JOYSTICK_DINPUT aren't being defined.

**Comment by bigboo3000** [comment]
it's a FC30 pro (the japanese version) exactly, maybe it's the problem?
Also firmware have been updated many times on this pad, maybe it changed something

**Comment by inolen** [comment]
@bigboo3000 hmph, unfortunately I can't really debug without the pad. If the pad is in xinput mode, afaik, none of this should matter as xinput is standardized and it should find the default xinput pad.

This makes me think SDL_JOYSTICK_XINPUT isn't defined on your machine. Do you have the Directx SDK installed?

As a start, you could search through the build directory for SDL_JOYSTICK_XINPUT, and you could also look for xinput.h on your local machine.

**Comment by bigboo3000** [comment]
Yes I have DirectX Redist installed, it's needed for Retroarch, but not DirectX SDK.
It's not a problem since I will use the libretro core in the long term if you update it regulary.

**Comment by mohsinous** [comment]
@inolen does Xiaomi Mi Gamepad Support by Redream!!? i am really confused why it doesnt recognize!

**Comment by inolen** [comment]
@mohsinous because its not supported by SDL's gamepad database, it's not currently supported by redream.

The ability to bind custom controllers will come, it's just not a priority being that SDL's gamepad database covers most common controllers.

**Comment by mohsinous** [comment]
thanks a lot for answering!!
the new build has removed GUI!! may i ask why!?

**Comment by inolen** [comment]
@bigboo3000 I've fixed an issue in the build that was disabling DirectX support. The Windows builds should now work with your gamepad, @mohsinous yours may work as well.

Regarding the removed menu options, they were removed as I'm preparing to release the new UI soon.

**Comment by bigboo3000** [comment]
Yep gamepad works correctly now.

**Comment by mohsinous** [comment]
amazing, work out of the box even without scpdriver and spoofing things!!! u r the man!!

**Comment by mohsinous** [comment]
about UI, the first one was good but i am sure the next one will be perfect!! again thank you for bringing us THE Redream.
