### ISSUE TITLE
Propeller Arena (Unreleased).cdi - unsupported TRAPA

### ISSUE THREAD

**Issue by bigboo3000** [inolen/redream#183]
It goes back to bios menu

![propellerarena](https://user-images.githubusercontent.com/16479698/31315003-85fd2c70-ac0e-11e7-8747-ad9450336527.png)

pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
bios_override_settings region=usa lang=english bcast=ntsc
audio_create_device latency=50 ms/2205 frames
imgui_update_font_tex w=512 h=64
dc_load path=D:\Emulation\Archives\consoles_discs\dreamcast\Propeller Arena (Unreleased).cdi
cdi_parse version 2 detected
cdi_parse found 2 sessions
cdi_parse_track track=1 fad=150 off=350400 mode=M2F1/2336
cdi_parse_track track=2 fad=357166 off=808059776 mode=M2F1/2336
disc_create id=PROPELLER ARENA PROPER by atreyu187                                                MK-51162 V1.006 GD-ROM1/1
sh4_ccn_reset
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=260 vbend=336
arm7_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
arm7_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
arm7_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36

**Comment by inolen** [comment]
The game should now at least boots after the latest cdi changes, but asserts early on.

**Comment by bigboo3000** [comment]
no it still go back to bios with the same unrecognized disk like the first image here and the log is still the same:

pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
bios_override_settings region=usa lang=french bcast=ntsc time=0x7fab7536
audio_create_device latency=92 ms/4096 frames
imgui_update_font_tex w=512 h=64
dc_load path= \Propeller Arena (Unreleased).cdi
cdi_parse version 2 detected
cdi_parse found 2 sessions
cdi_parse_track track=1 fad=150 off=350400 mode=MODE2/2336
cdi_parse_track track=2 fad=357166 off=808059776 mode=MODE2/2336
disc_create id=PROPELLER ARENA PROPER by atreyu187                                                MK-51162 V1.006 GD-ROM1/1
sh4_ccn_reset
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=260 vbend=336
arm7_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
arm7_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
arm7_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36

**Comment by inolen** [comment]
TRAPA is still a problem, but boots on Windows with 2dacdc06077250acfc58f8510dcea3ec6c0557ed and 3f1de035572b8dd3d3cff714a24df814648c68ec

**Comment by bigboo3000** [comment]
yes I change the issue title.
unsupported TRAPA

**Comment by bigboo3000** [comment]
closed and linked to https://github.com/inolen/redream/issues/166
