### ISSUE TITLE
Record of Lodoss War (France/PAL) graphical glitches

### ISSUE THREAD

**Issue by bigboo3000** [inolen/redream#184]
in the display screen:

demul:
![recordoflodosswar1_demul](https://user-images.githubusercontent.com/16479698/31319106-cd722c3c-ac5d-11e7-9edf-8f33c9bed59d.png)

redream (there is nothing in the 50hz rectangle)
![recordoflodosswar1_redream](https://user-images.githubusercontent.com/16479698/31319111-e24466a2-ac5d-11e7-948d-a98caacd9c05.png)

ingame:

demul:
![recordoflodosswar2_demul](https://user-images.githubusercontent.com/16479698/31319113-ec0da482-ac5d-11e7-8f60-9544f0dfdb88.png)

redream:
![recordoflodosswar2_redream](https://user-images.githubusercontent.com/16479698/31319116-f3dd935c-ac5d-11e7-9be1-01d02725fea9.png)

**Comment by inolen** [comment]
Regarding the second issue, I believe it should be fixed with https://github.com/inolen/redream/commit/ba5c4e8685c69bee84d18d371148d986f1e2512e.

The first issue is the same as https://github.com/inolen/redream/issues/113 I believe.

**Comment by inolen** [comment]
That looks to be a different issue. #113 is related to alpha polygons just being sorted incorrectly.

**Comment by inolen** [comment]
There's a small chance that https://github.com/inolen/redream/commit/f6dbdbcd0286298884e7f8502facd77358561d55 may fix that menu. If it doesn't, it'd be helpful to have a trace from that scene (emu -> start trace / emu -> stop trace when done) as I don't have a copy of this game.

**Comment by literalmente-game** [comment]
Fixed by https://github.com/inolen/redream/commit/f6dbdbcd0286298884e7f8502facd77358561d55
![redream010 2017-10-20 00-10-54-50](https://user-images.githubusercontent.com/24926584/31802165-520ce588-b52b-11e7-9e3f-f37cb384321f.png)

**Comment by inolen** [comment]
I believe https://github.com/inolen/redream/commit/7fabdb44ce771a8219a1187cc407f4d02c0d5b5f should now fix the first scene as well.

**Comment by bigboo3000** [comment]
ok everything is fine now, thanks!
