### ISSUE TITLE
Only show C: drive new GUI - Windows Build

### ISSUE THREAD

**Issue by tabnk** [inolen/redream#186]
Tried to add directory from your new GUI but only show C: drive.

Tested on latest (2 days ago) https://github.com/inolen/redream/releases/download/ci-latest/redream.x86_64-windows-HEAD.tar.gz

**Comment by inolen** [comment]
This (and other reasons) are why this branch have yet to be merged to master.

What drives are missing?

**Comment by tabnk** [comment]
All drive except C:.

**Comment by inolen** [comment]
Right, but what drives do you have that you are expecting to see? Regular drives, network mounts, ...?

**Comment by tabnk** [comment]
Local drive D: but didn’t shown on UI. Only C: appeared.

**Comment by RinMaru** [comment]
same here using the Latest build I have my CHD's on Ext Drive F. and Redream will Crash if you select a folder with any CHD files in it. but you can launch CHD's by having them open with Redream

**Comment by inolen** [comment]
Huh? Are you building the ui branch or something? This feature isn't available on the downloadable binaries.

**Comment by RinMaru** [comment]
im using what is in the release tab

**Comment by inolen** [comment]
Heh, that is not intended to be public right now, looks like the CI was building from the ui branch instead of master.

**Comment by RinMaru** [comment]
Love the UI though and this project your doing a great job ^^

**Comment by inolen** [comment]
This should be fixed with latest, and the ui work is now part of the master branch.
