### ISSUE TITLE
Error compiling due to deprecation

### ISSUE THREAD

**Issue by Kazade** [inolen/redream#19]
```
/home/lukeb/Git/redream/deps/eigen-3.2.1/Eigen/src/Core/../plugins/ArrayCwiseUnaryOps.h:192:30: error: ‘template<class _Operation> class std::binder2nd’ is deprecated [-Werror=deprecated-declarations]
     return CwiseUnaryOp<std::binder2nd<FUNCTOR<Scalar> >, const Derived> \
```

I'm getting this while compiling on Fedora 23 with GCC 5.3.1

**Comment by inolen** [comment]
I only use the Eigen dependency in 1 or 2 places, and I've been planning to remove it. I'll try to get around to ripping it out this weekend.

**Comment by inolen** [comment]
Went ahead and updated Eigen to 3.2.8 in hopes they'd maybe sorted out the compile issue.

**Comment by Kazade** [comment]
Nah, same thing :(

It's OK, I can wait - I had a quick look at it seems you only use Eigen for Matrix4f, is that right?

If I can find a second later I'll try to come up with a PR.

**Comment by inolen** [comment]
Yup, it's used for _extremely_ minor things. I'd be fine adding a float mat4x4[16] type to `math.h` and some basic `mat4x4_ident`, `mat4x4_transpose`, etc. methods there.

**Comment by Kazade** [comment]
I can probably just copy paste some stuff from my math library :) https://github.com/kazade/kazmath

**Comment by inolen** [comment]
I'm down with replacing Eigen with that. I actually much prefer working with C-style libraries for this type of work.

**Comment by inolen** [comment]
https://github.com/inolen/redream/issues/21

**Comment by gbirchley** [comment]
@Kazade - apologies for bumping the thread, but I'm also trying to build in Fedora 23 and encountering this issue. Did you successfully work around this problem?

**Comment by inolen** [comment]
Closing this now. I've spent the past month converting the code base to C, which managed to organically solve this ;) Compiled and ran with Fedora 24 tonight.
