### ISSUE TITLE
Cool Cool Toon (Japan) doesn't load

### ISSUE THREAD

**Issue by literalmente-game** [inolen/redream#190]
Last line before closing Redream was:
[C:\projects\redream\src\guest\gdrom\disc.c:94] Check failed: track must be non-NULL

Tested using https://github.com/inolen/redream/commit/9926e82a82d2d5ede22a4a48983ab1bfac5a1c87
Windows 7
Same behavior with HLE/Real BIOS

**Comment by inolen** [comment]
Was this a CDI or GDI? It looks like a problem with parsing the disc.

**Comment by literalmente-game** [comment]
CDI.
Log:

E:\Emulators\Dreamcast\NU>redream5.exe --bios=boot.bin --flash=dc_flash.bin "Coo
l Cool Toon.cdi"
boot_load_rom loaded 'C:\Users\--USER--\.redream\boot.bin'
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hc
ount=857 interlace=0 vbstart=260 vbend=336
bios_override_settings region=japan lang=english bcast=ntsc time=0x7f7ecce8
audio_create_device latency=50 ms/2205 frames
imgui_update_font_tex w=512 h=64
dc_load path=Cool Cool Toon.cdi
cdi_parse version 3.5 detected
cdi_parse found 2 sessions
cdi_parse_track track=1 fad=150 off=352800 mode=CDDA/2352
cdi_parse_track track=2 fad=11852 off=1413504 mode=M2F1/2336
disc_create id=COOL COOL TOON T3106M V1.012 GD-ROM1/1
sh4_ccn_reset
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hc
ount=857 interlace=0 vbstart=260 vbend=336
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=260 vbend=336
arm7_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
arm7_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
[C:\projects\redream\src\guest\gdrom\disc.c:94] Check failed: track must be non-
NULL

**Comment by inolen** [comment]
Fixed with 2dacdc06077250acfc58f8510dcea3ec6c0557ed.
