### ISSUE TITLE
Dux doesn't load

### ISSUE THREAD

**Issue by literalmente-game** [inolen/redream#191]
Tested using 9926e82
Windows 7
Same behavior with HLE/Real BIOS

Log: 

E:\Emulators\Dreamcast\NU>redream5.exe --bios=boot.bin --flash=dc_flash.bin "DUX.cdi"
boot_load_rom loaded 'C:\Users\--USER--\.redream\boot.bin'
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hc
ount=857 interlace=0 vbstart=260 vbend=336
bios_override_settings region=japan lang=english bcast=ntsc time=0x7f807cd9
audio_create_device latency=50 ms/2205 frames
imgui_update_font_tex w=512 h=64
dc_load path=DUX.cdi
cdi_parse version 3.5 detected
cdi_parse found 2 sessions
cdi_parse_track track=1 fad=150 off=352800 mode=CDDA/2352
cdi_parse_track track=2 fad=12378 off=29113056 mode=CDDA/2352
cdi_parse_track track=3 fad=22130 off=52049760 mode=CDDA/2352
cdi_parse_track track=4 fad=40878 off=96145056 mode=CDDA/2352
cdi_parse_track track=5 fad=50630 off=119081760 mode=CDDA/2352
cdi_parse_track track=6 fad=63079 off=148361808 mode=CDDA/2352
cdi_parse_track track=7 fad=72831 off=171298512 mode=CDDA/2352
cdi_parse_track track=8 fad=88376 off=207860352 mode=CDDA/2352
cdi_parse_track track=9 fad=98128 off=230797056 mode=CDDA/2352
cdi_parse_track track=10 fad=112151 off=263779152 mode=CDDA/2352
cdi_parse_track track=11 fad=121903 off=286715856 mode=CDDA/2352
cdi_parse_track track=12 fad=132859 off=312484368 mode=CDDA/2352
cdi_parse_track track=13 fad=142611 off=335421072 mode=CDDA/2352
cdi_parse_track track=14 fad=146363 off=344245776 mode=CDDA/2352
cdi_parse_track track=15 fad=156782 off=368751264 mode=CDDA/2352
cdi_parse_track track=16 fad=162569 off=382362288 mode=CDDA/2352
cdi_parse_track track=17 fad=163492 off=384533184 mode=CDDA/2352
cdi_parse_track track=18 fad=179458 off=395622816 mode=M2F1/2336
disc_create id=DUX T0000 V1.000 CD-ROM1/1
sh4_ccn_reset
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hc
ount=857 interlace=0 vbstart=260 vbend=336
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=260 vbend=336
arm7_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
arm7_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
[C:\projects\redream\src\guest\gdrom\disc.c:95] Check failed: sector_fmt == GD_SECTOR_ANY || sector_fmt == track->sector_fmt

**Comment by inolen** [comment]
Looks to be related to #91.

**Comment by inolen** [comment]
I don't have a copy of this game, but I believe this should be fixed as of 3f1de035572b8dd3d3cff714a24df814648c68ec.

**Comment by bigboo3000** [comment]
this issue is fixed but now there is another problem, the game crashes just after the sega licence screen:

sh4_area0_write unexpected addr 0x00000000

**Comment by inolen** [comment]
Fixed with https://github.com/inolen/redream/commit/830274e6a9213faf99b1dd325563624b5850542c.

**Comment by bigboo3000** [comment]
fixed for me too
