### ISSUE TITLE
Shenmue (USA) stuck at Ryo's room loading Screen

### ISSUE THREAD

**Issue by mohsinous** [inolen/redream#192]
![2017-10-15_13-13-44](https://user-images.githubusercontent.com/32609205/31583557-efb0ddfa-b1aa-11e7-965a-46e821093c93.jpg)
as you see redream stuck here and does't go any further.

**Comment by twinaphex** [comment]
It's the same with Reicast.

**Comment by mohsinous** [comment]
I just test it in demul and the runs ok. no problem with demul!!!!!!!!

**Comment by inolen** [comment]
Closing as a duplicate of https://github.com/inolen/redream/issues/118
