### ISSUE TITLE
Cheat Engine 6.7 Doesn't Work

### ISSUE THREAD

**Issue by mohsinous** [inolen/redream#195]
I just wanted to test cheat engine with redream and unfortunately it did not work. i tested it with demul and it did work!!! why!!!!?

**Comment by literalmente-game** [comment]
Cheat Engine is an external tool to find and replace memory addresses in real time where you need to find the exact adresses and values for it to work. Needless to say, this program is 0% related do Redream, any problem you have with it is a problem with Cheat Engine (or you not knowing how to use Cheat Engine properly), not Redream

**Comment by mohsinous** [comment]
i know how to use cheat engine but with redream it didnt find any value!!! So strange
