### ISSUE TITLE
There is no Analogue Stick mapping for Keyboard

### ISSUE THREAD

**Issue by mohsinous** [inolen/redream#196]
in Fighting Force 2 Analogue Stick is movement and DPAD is 180' return. AWSD key are DPAD and no Analogue Stick key are mapped for keyboard input!!!

**Comment by inolen** [comment]
This is true, and there's already an issue for this:
https://github.com/inolen/redream/issues/141

While creating issues is helpful, do realize that duplicate issues spams e-mails to everyone who's setup to receive e-mail notifications when issues are created.
