### ISSUE TITLE
Latest Redream crash on Fighting Force 2

### ISSUE THREAD

**Issue by mohsinous** [inolen/redream#197]
C:\Users\Admin\Desktop\Fighting Force 2 (Europe)>redream dc.gdi
boot_load_rom loaded 'C:\Users\Admin\.redream\boot.bin'
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hc
ount=857 interlace=0 vbstart=260 vbend=336
bios_override_settings region=usa lang=english bcast=ntsc time=0x7f871daa
audio_create_device latency=50 ms/2205 frames
imgui_update_font_tex w=512 h=64
dc_load path=dc.gdi
gdi_parse track=1 filename='.\Fighting Force 2 (Europe) (En,Fr) (Track 1).bin' f
ad=150 secsz=2352
gdi_parse track=2 filename='.\Fighting Force 2 (Europe) (En,Fr) (Track 2).bin' f
ad=600 secsz=2352
gdi_parse track=3 filename='.\Fighting Force 2 (Europe) (En,Fr) (Track 3).bin' f
ad=45150 secsz=2352
gdi_parse track=4 filename='.\Fighting Force 2 (Europe) (En,Fr) (Track 4).bin' f
ad=224879 secsz=2352
gdi_parse track=5 filename='.\Fighting Force 2 (Europe) (En,Fr) (Track 5).bin' f
ad=226310 secsz=2352
gdi_parse track=6 filename='.\Fighting Force 2 (Europe) (En,Fr) (Track 6).bin' f
ad=232260 secsz=2352
disc_create id=FIGHTING FORCE 2 36802D 80 V1.000 GD-ROM1/1
sh4_ccn_reset
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hc
ount=857 interlace=0 vbstart=260 vbend=336
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=260 vbend=336
arm7_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
arm7_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
arm7_reset
sh4_ccn_reset
arm7_reset
sh4_ccn_reset
arm7_reset
[C:\projects\redream\src\core\memory.c:112] Check failed: protect_pages((void *)
aligned_begin, aligned_size, ACC_READONLY)

I can confirm the one before was running the game perfectly!!!

**Comment by inolen** [comment]
I'll give it a spin on Windows tonight and see if I can repro.

**Comment by mohsinous** [comment]
@inolen dont mention it man.

**Comment by literalmente-game** [comment]
The game is able to boot, the crash happens after the "New Game" cutscene, right before you're able to control your character

**Comment by mohsinous** [comment]
@literalmente-game yeah off course!! i just havent time to describe completely!!!!

**Comment by mohsinous** [comment]
the latest build ( 166bc1b ) wont run FF2 at all!!!! so weird!!!
D:\Fighting Force 2 (Europe)>redream dc.gdi
fs_set_appdir path=C:\Users\Fatemeh\.redream
failed to load 'C:\Users\Fatemeh\.redream\boot.bin'
failed to open flash rom 'C:\Users\Fatemeh\.redream\flash.bin'
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hc
ount=857 interlace=0 vbstart=260 vbend=336
bios_validate_flash resetting FLASH_PT_FACTORY
bios_validate_flash resetting FLASH_PT_USER
bios_validate_flash resetting FLASH_PT_GAME
bios_validate_flash resetting FLASH_PT_UNKNOWN
bios_override_settings region=usa lang=english bcast=ntsc time=0x7f87f649
audio_create_device latency=50 ms/2205 frames
imgui_update_font_tex w=512 h=64
dc_load path=dc.gdi
gdi_parse track=1 filename='.\Fighting Force 2 (Europe) (En,Fr) (Track 1).bin' f
ad=150 secsz=2352
gdi_parse track=2 filename='.\Fighting Force 2 (Europe) (En,Fr) (Track 2).bin' f
ad=600 secsz=2352
gdi_parse track=3 filename='.\Fighting Force 2 (Europe) (En,Fr) (Track 3).bin' f
ad=45150 secsz=2352
gdi_parse track=4 filename='.\Fighting Force 2 (Europe) (En,Fr) (Track 4).bin' f
ad=224879 secsz=2352
gdi_parse track=5 filename='.\Fighting Force 2 (Europe) (En,Fr) (Track 5).bin' f
ad=226310 secsz=2352
gdi_parse track=6 filename='.\Fighting Force 2 (Europe) (En,Fr) (Track 6).bin' f
ad=232260 secsz=2352
disc_create id=FIGHTING FORCE 2 36802D 80 V1.000 GD-ROM1/1
bios_boot using hle bootstrap
sh4_ccn_reset
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hc
ount=857 interlace=0 vbstart=260 vbend=336
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
sh4_ccn_reset
sh4_ccn_reset
[C:\projects\redream\src\guest\memory.c:394] Check failed: size  == 0

**Comment by mohsinous** [comment]
the latest build ( 166bc1b ) has the same problem as the previous one!!!!! so weird

**Comment by inolen** [comment]
Should be fixed with https://github.com/inolen/redream/commit/747fddb805f4e25f2a62e43c66c8889535848f59.
