### ISSUE TITLE
redream does not run on Ubuntu 17.1

### ISSUE THREAD

**Issue by mohsinous** [inolen/redream#198]
when i run redream i got this error

mohsen@mohsen-pc:~/Downloads/redream.x86_64-linux-HEAD$ ./redream
fs_set_appdir path=/home/mohsen/.redream
boot_load_rom loaded '/home/mohsen/.redream/boot.bin'
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
bios_override_settings region=usa lang=english bcast=ntsc time=0x7f88a5c6
audio_create_device failed to open device: No such audio device
audio_init failed to open audio device: No such audio device
imgui_update_font_tex w=512 h=64
Segmentation fault (core dumped)

**Comment by mohsinous** [comment]
and after updating some libs it show me this

audio_create_device failed to open device: Fragment size must be a power of two
audio_init failed to open audio device: Fragment size must be a power of two

  instead of

audio_create_device failed to open device: No such audio device
audio_init failed to open audio device: No such audio device

**Comment by inolen** [comment]
Should be fixed with https://github.com/inolen/redream/commit/c662ab20225afb6230d877a4598b6e44261a74b8.

**Comment by mohsinous** [comment]
![2](https://user-images.githubusercontent.com/32609205/31880673-2849abf8-b7ee-11e7-8d59-1ccf7e121afd.jpg)


tested with latest build ( 1aa0dbf )

**Comment by inolen** [comment]
Oh, are you running the precompiled binaries here?

I may not be precompiling with support for all of the possible audio backends.

**Comment by mohsinous** [comment]
@inolen yes, i use precompile build!! even on windows

**Comment by inolen** [comment]
Latest Linux binaries should have support for alsa, pulseaudio and jack.

**Comment by inolen** [comment]
Did you have a chance to test these latest binaries?

**Comment by mohsinous** [comment]
@inolen checked it with linux mint 18 and it did work well
