### ISSUE TITLE
Death Crimson OX almost unplayable with the keyboard after control changes

### ISSUE THREAD

**Issue by literalmente-game** [inolen/redream#199]
After https://github.com/inolen/redream/commit/6e9f8b9ddb399cc5e8a14d3902f92659d9fefaa8, pressing UP will make the aim shows up on the top of the screen instead of going slowly to the top (that was the behavior before the change), the same goes for all the directions. A solution should be binding D-Pad and the analog stick to different keys (WASD for D-Pad + keyboard arrows for the analog).

**Comment by inolen** [comment]
@literalmente-game is there some common keyboard mapping for this setup?

I just kind of view the keyboard as a second-class debugging citizen, but I'm game for finding a suitable default that matches up with other emulators and what not.

**Comment by literalmente-game** [comment]
Citra uses the arrow keys for the Circle Pad + FHTG for the D-Pad.
RPCS3 uses the arrow keys for D-Pad + WASD for left analog + Home/End/PageUp/PageDown for right analog.
PPSSPP uses the arrow keys for the D-Pad + IKJL for the analog stick.
Dolphin uses the arrow keys for the D-Pad + WASD for the Nunchuck analog.

WASD + Arrows seems like a good choice in general

**Comment by inolen** [comment]
So then, leave the left analog on WASD, but move DPAD to arrow keys as a default?

What do other emulators do for A/B/X/Y?

**Comment by literalmente-game** [comment]
These buttons are different from emulator to emulator, but most of the time they are set on the keys on the left lower corner of the keyboard (what would not be very comfortable when using WASD + Arrows).

For reference:
Citra: ASZX
PPSSPP: XZAS
RPCS3:  VZXC
Dolphin: ZXCS

**Comment by mohsinous** [comment]
same problem here with keyboard mapping

**Comment by inolen** [comment]
@literalmente-game hmph, as a PC gamer, those binds don't seem very nice.

I think keeping the directional inputs on the left, buttons on the right seems sane, but we need to have a good default for the dpad as well as the analog stick since some games use either or as the primary movement input.

Without diving too far off the deepend (e.g. some kind of toggle to make wasd behave as either the dpad or analog), I think the easiest short-term fix is
WASD - analog
TFGH - dpad
OKPL - axby (shifted over from IJKL as it is now to give a bit more room)

**Comment by inolen** [comment]
Only last question would be - what should the triggers map to by default in that setup? `[` and `]`?

**Comment by literalmente-game** [comment]
1 and 2, [ and ], 9 and 0, Q and E are all good choices

**Comment by inolen** [comment]
Updated default keybinds with https://github.com/inolen/redream/commit/f55114d2610d418becbf9dcb739b685347a412e2.

**Comment by literalmente-game** [comment]
The game is playable again with https://github.com/inolen/redream/commit/f55114d2610d418becbf9dcb739b685347a412e2
