### ISSUE TITLE
Dreamcast BIOS looks ugly

### ISSUE THREAD

**Issue by mohsinous** [inolen/redream#200]
![1](https://user-images.githubusercontent.com/32609205/31879282-d059c8c8-b7e9-11e7-93db-2d599381f6c9.jpg)
AMD A8-6500
AMD 8570D onboard VGA
8GB RAM
Windows 8.1 x64

**Comment by bigboo3000** [comment]
you need to change aspect in config file to 4:3 instead of strech
aspect: 4:3
(I think 4:3 should be the default because I don't think there are 16:9 games)

**Comment by mohsinous** [comment]
no, look at the icons (zoom in to see better) there are glitches on icons!!

**Comment by inolen** [comment]
This is a side effect of changes submitted to close https://github.com/inolen/redream/issues/113 over the weekend.

For _most_ cases, I believe the current solution is "good enough" with respect to visuals / performance.

In cases like this where they were showing off their order-independent transparency, things may look less than desirable. However, I think some minor visual artifacting in these edge cases is more desirable than the major artifacting that was going on before https://github.com/inolen/redream/commit/7fabdb44ce771a8219a1187cc407f4d02c0d5b5f.

I'd be happy to have a more accurate, performance-intensive option for #113, but let's talk about that in that bug if anyone ever has the time to work on it.
