### ISSUE TITLE
Headhunter closes Redream after Stern Mansion

### ISSUE THREAD

**Issue by mohsinous** [inolen/redream#202]
D:\HeadHunter>redream dc.gdi
fs_set_appdir path=C:\Users\Fatemeh\.redream
boot_load_rom loaded 'C:\Users\Fatemeh\.redream\boot.bin'
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hc
ount=857 interlace=0 vbstart=260 vbend=336
bios_override_settings region=europe lang=english bcast=pal time=0x7f8e4b87
audio_create_device latency=92 ms/4096 frames
imgui_update_font_tex w=512 h=64
input_controller_added port=0 name=XiaoMi Game Controller
dc_load path=dc.gdi
gdi_parse track=1 filename='.\track01.bin' fad=150 secsz=2352
gdi_parse track=2 filename='.\track02.raw' fad=600 secsz=2352
gdi_parse track=3 filename='.\track03.bin' fad=45150 secsz=2352
disc_create id=HEADHUNTER - SEGA - AMUZE - 2001 MK-5104150 V1.006 GD-ROM1/2
input_controller_added port=1 name=XiaoMi Game Controller
sh4_ccn_reset
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hc
ount=857 interlace=0 vbstart=260 vbend=336
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=260 vbend=336
arm7_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
arm7_reset
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
arm7_reset
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
pvr_reconfigure_spg mode=PAL pixel_clock=13500000 line_clock=31250 vcount=624 hc
ount=863 interlace=1 vbstart=620 vbend=44
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=620 vbend=44
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 h
count=857 interlace=1 vbstart=516 vbend=36
imgui_update_font_tex w=512 h=64
imgui_update_font_tex w=512 h=64
[C:\projects\redream\src\guest\pvr\tex.c:643] Check failed: !compressed

by the way, the latest build fix an issue that vmu icon were not display when i want to load!!

**Comment by inolen** [comment]
I believe this should be fixed with https://github.com/inolen/redream/commit/414c290f806eefcd21ded4f87cc80e92dd8137d6.

**Comment by inolen** [comment]
Closing this. While I haven't test this game, the assert at this line is resolved. Please reopen if it's still an issue for you.
