### ISSUE TITLE
Various rendering issues

### ISSUE THREAD

**Issue by Shoegzer** [inolen/redream#203]
During testing against latest (Oct. 26) redream build, I observed several graphics glitches as noted below.  Most of these were observed with prior versions too, but I wanted to be sure they were captured somewhere.

Alien Front Online: Green polygon occluding most of the screen:
![alient front online](https://user-images.githubusercontent.com/12475371/32139121-f03f0f8a-bc0e-11e7-85f3-57554742f1c6.png)

Dragon's Blood: Pink sky:
![dragon s blood](https://user-images.githubusercontent.com/12475371/32139125-01f45e1a-bc0f-11e7-8fa6-0261ae4f8e32.png)

Hydro Thunder: Black area under player's boat:
![hydro thunder](https://user-images.githubusercontent.com/12475371/32139129-0d9b5a3e-bc0f-11e7-89e1-f56f3d72e0c1.png)

Maken X: Black area covering most of game screen:
![maken x](https://user-images.githubusercontent.com/12475371/32139131-17d8849a-bc0f-11e7-96e4-34cd3e273ff3.png)

Record of Lodoss War: Radar in lower-left is wrong:
![record of lodoss war](https://user-images.githubusercontent.com/12475371/32139133-22402de8-bc0f-11e7-83af-c962da7751d4.png)

Red Dog: Green areas over game screen:
![red dog](https://user-images.githubusercontent.com/12475371/32139142-4e991bd4-bc0f-11e7-9248-b49f4b4bb381.png)

Soul Calibur: Silver columns in fights:
![soul calibur](https://user-images.githubusercontent.com/12475371/32139145-5989aed2-bc0f-11e7-9437-f0db947c3456.png)

Sword of the Beserk: In-game effects are wrong:
![sword of the beserk](https://user-images.githubusercontent.com/12475371/32139150-6e517a52-bc0f-11e7-943d-7c6945bfd236.png)

**Comment by literalmente-game** [comment]
I don't know about Alien Front Online or Sword of the Beserk, but the other games don't show those issues for me, are you SURE you're using the last build? Try downloading the build from one hour ago and try the games again. Also, care to provide your OS and PC specs?

**Comment by Shoegzer** [comment]
Yes, I'm sure.  As I stated, I used an Oct. 26 build, and nothing graphically has changed since then.  The system I tested against is Linux Mint 18.2 x64, kernel 4.11, with Haswell, Nvidia 860M and 384.90 drivers.

**Comment by literalmente-game** [comment]
Windows 7 + NVidia GTX 460 SE (388.13 drivers). I don't think that the pink sky on the Dragon's Blood shot is a real problem, Redream still don't emulate the fog that is supposed to be covering that part of the level (you shoudn't be able to see that far on the real hardware, there is a slightly green fog). For Maken X, Record of Lodoss War and Soul Calibur, check the https://github.com/inolen/redream/wiki/Compatibility , I've included gameplay footage for the games + what build has been used in each test.

**Comment by Shoegzer** [comment]
Agreed on the Dragon's Blood/pink sky issue - that's possibly corrected through accurate emulation of fogging effects though we won't know for sure until those effects are emulated.

On the others - please note your specific OS/HW/driver configurations in the comments column below where you have "Playable".  It's currently misleading and the graphics issues will need to be fixed for those configurations that aren't yours.  At the very least it will encourage others to test their own configurations and report results.

**Comment by literalmente-game** [comment]
Those informations alone would fill the entire list making it a big mess, I'll think of some way to present this on an organized fashion. I don't think it's misleading when I've received reports from different configurations running the same games without most of the issues you've presented, seems like you're a single case so far (until someone else is able to reproduce this, the issue should still be open for comparisons + new reports on the same problems).

**Comment by inolen** [comment]
@Shoegzer what would be really helpful to me is a quick trace (emu -> start trace / emu -> stop trace) from one of these bad scenes.

**Comment by Shoegzer** [comment]
@literalmente-game thanks for your thoughts.  All i'm saying is to post a quick note about the OS/HW used to observe those games as playable, since there are varying results.  That's no more of a mess than any other notes posted for other games in that same column.  Also could you indicate what reports you've received other than your own?  It sounds like you've got a team of testers there.  ;)

@inolen sure, happy to do that.  putting it together for you...

**Comment by inolen** [comment]
Grabbed his trace, looked bad on my machine, while my trace looked good on his machine.

Assuming this is possibly some JIT oddity on your CPU.

**Comment by Shoegzer** [comment]
Yup, and again I'm on a Haswell proc.  We'll do some more testing soon and nail this thing down.  Thanks for working on it.

**Comment by bigboo3000** [comment]
I just tested some games and I can confirm this on my machine:

Alien Front online obvious graphic coruption
![image](https://user-images.githubusercontent.com/16479698/33061849-cf009a5e-ce9d-11e7-83b8-45a93429483a.png)

Dragon's blood (but yes It look likes missing fog support)
![image](https://user-images.githubusercontent.com/16479698/33062770-c32d3dc4-cea0-11e7-9154-b6cc6f2a3343.png)

Hydro Thunder black area under boat (it's less obvious in my screenshot but it's easy to see when playing)
![image](https://user-images.githubusercontent.com/16479698/33062177-a7bf9930-ce9e-11e7-8fda-e49b2d2c6641.png)

But all other games are fine for me.
On your screenshots Red Dog and Soulcalibur look like some kind of overclocking corruption, it's very strange.

**Comment by inolen** [comment]
The primary issue (Red Dog, Soul Calibur) here is fixed with https://github.com/inolen/redream/commit/86205daf1ba2a353270b425888c14127655d47db.
