### ISSUE TITLE
Plasma Sword - Nightmare of Bilstein (USA) not able to boot

### ISSUE THREAD

**Issue by literalmente-game** [inolen/redream#204]
Build https://github.com/inolen/redream/commit/3ebfbe47cc8f59befc199312f77d75ae526e1985

[log.txt](https://github.com/inolen/redream/files/1427920/log.txt)

**Comment by inolen** [comment]
The initial issue looks like https://github.com/inolen/redream/blob/master/src/guest/gdrom/disc.h#L9 just needs to be upped (say, 128).

**Comment by literalmente-game** [comment]
The game is now able to boot, fixed with https://github.com/inolen/redream/commit/5e35a2649fc626378e3336f542fe7152925cdf15
