### ISSUE TITLE
Twinkle Star Sprites (J) unplayable due to heavy sprite corruption

### ISSUE THREAD

**Issue by literalmente-game** [inolen/redream#209]
GDI format used.
Windows 7
Build: https://github.com/inolen/redream/commit/ffc48584f1b6838717291a1bfd18519294d1a14a
Log: [log.txt](https://github.com/inolen/redream/files/1463447/log.txt)
Trace (from the game first screen until the first in-game screen): http://www.mediafire.com/file/xd3wv7xqsk73181/0.7z

Screenshot (Menu):
![redream017 2017-11-11 02-39-31-71](https://user-images.githubusercontent.com/24926584/32686502-0e6ac444-c68d-11e7-920c-ad61211fba89.png)

Screenshot (in-game):
![redream017 2017-11-11 02-39-35-40](https://user-images.githubusercontent.com/24926584/32686518-29c3ea22-c68d-11e7-8610-9687b04c9494.png)

**Comment by inolen** [comment]
It looks like the textures here are fine, but the polygons are rendered as sprites and the UV coordinates are messed up.

**Comment by inolen** [comment]
This has been a backburner task for ages, resolved with 4713a1871192cf35b406f6faa71d901c8586efbb.

**Comment by literalmente-game** [comment]
Something caused the build to fail (at least for Windows). I'll test it to confirm as soon as the build is out

**Comment by literalmente-game** [comment]
Tested it now, I'm able to reach in-game with sprites rendering correctly (I've found another issue with this game, but I guess it's unrelated). Fixed with https://github.com/inolen/redream/commit/4713a1871192cf35b406f6faa71d901c8586efbb

**Comment by inolen** [comment]
Please do post another issue for whatever else came up.

**Comment by literalmente-game** [comment]
Don't worry, I'm retesting each game with each new issue to see the progress/regressions. Anything weird happens I'll open an issue ;)
