### ISSUE TITLE
black texture bug in standalone redream not present in libretro core

### ISSUE THREAD

**Issue by bigboo3000** [inolen/redream#210]
I tested some games and I found a bug only present in standalone.
I think this bug is here since https://github.com/inolen/redream/commit/3243219bcf8c1bd29ffd060e05695c595574861b

In standalone many textures are completely black, the most obvious case I found is intro and title screen of Capcom vs. SNK - Millennium Fight 2000 Pro (Japan). The intro is almost completely black in standalone and here is the title screen:

standalone
![redream_standalone](https://user-images.githubusercontent.com/16479698/32688466-8005f382-c6d1-11e7-950e-b01ec817daad.png)
 
libretro core
![capcom vs snk - millennium fight 2000 pro japan -171111-110750](https://user-images.githubusercontent.com/16479698/32688473-94ffd280-c6d1-11e7-9596-45e1a116a865.png)

This problem is also found in other games (intro of soulcalibur, Tony Hawk 2, etc.)

I used latest redream standalone and libretro core.
I tested this on 2 computers with windows 10 creators update, one with radeon r270x latest driver, and one with intel HD 620 latest driver with same results.

**Comment by inolen** [comment]
Hmph, so on my computer it looks like:
![capcom](https://user-images.githubusercontent.com/460296/32689906-ed95cf06-c6ba-11e7-9f5b-3d993a1865dd.png)

Did you actually test the commit before https://github.com/inolen/redream/commit/3243219bcf8c1bd29ffd060e05695c595574861b to see if it was gone then?

It seems like an OpenGL issue given the fact that it works in libretro.

**Comment by bigboo3000** [comment]
I don't have an old version of redream anymore so I can't test it, but I remember that I first saw this problem with soulcalibur and THPS2 after this fix (I posted a comment on THPS2 problem 19 days ago, it should be the same bug)

**Comment by inolen** [comment]
I don't have time today, but tomorrow / next week I can help you bisect if you want. Do you happen to be on the slack channel?

**Comment by bigboo3000** [comment]
OK no problem and yes I can be on slack channel

**Comment by inolen** [comment]
@bigboo3000 could you do me a favor and capture a small trace from this scene? Would help know if it's OpenGL / a jit issue like Shoegazer has.

**Comment by bigboo3000** [comment]
Capcom vs. SNK - Millennium Fight 2000 Pro (Japan)
the log keeps repeating this:
mem_unhandled_read addr=0x5047b6bc
mem_unhandled_read addr=0x5047b6bc
mem_unhandled_read addr=0x5047b6bc
mem_unhandled_read addr=0x5047b6bc
mem_unhandled_read addr=0x5047b6bc
mem_unhandled_read addr=0x5047b6bc

the trace (it's big tell me if you want a smaller one)
https://we.tl/ieMgmmwbwp

**Comment by bigboo3000** [comment]
Just FIY I've tried Capcom vs. SNK - Millennium Fight 2000 **Pro** and based on your screenshot you have tried the non pro version, I don't know if its important.

**Comment by inolen** [comment]
Trace rendered fine for me, so this must be something related to setting up the OpenGL context I believe. Is there another game / screenshot you can so to give me something else to go off of?

**Comment by bigboo3000** [comment]
Virtua Striker 2 ver.2000.1 (Japan)
![image](https://user-images.githubusercontent.com/16479698/32692929-5ceaa38e-c721-11e7-90cf-103327e9b9b1.png)

**Comment by bigboo3000** [comment]
project justice
![image](https://user-images.githubusercontent.com/16479698/32692991-f018f9ca-c722-11e7-8329-16105d4d4156.png)

**Comment by inolen** [comment]
Thanks a lot! I was just able to repro on Windows.

**Comment by bigboo3000** [comment]
Good! I just found another one:
house of the dead 2
![image](https://user-images.githubusercontent.com/16479698/32693026-c7ea61ea-c723-11e7-8bd1-76be5257ea13.png)

**Comment by inolen** [comment]
Should be fixed with https://github.com/inolen/redream/commit/57e2558da90efcd122a1d695d684ffb0d438cb5d

**Comment by bigboo3000** [comment]
Yep it's fixed for me! That was fast thanks!

I don't think libretro build is broken because it has all the recent fixes like https://github.com/inolen/redream/commit/3243219bcf8c1bd29ffd060e05695c595574861b and Record of Lodoss War fixes.
