### ISSUE TITLE
Triggerheart Exelica (Japan) - completely crash redream.exe

### ISSUE THREAD

**Issue by bigboo3000** [inolen/redream#213]
Start the game, and when you are first shoot by a bullet redream.exe completely crash.
windows 10 creators update with intel HD620

**Comment by literalmente-game** [comment]
I've just tested the game here, finished 2 levels without any problem (using https://github.com/inolen/redream/commit/ffc48584f1b6838717291a1bfd18519294d1a14a ) . Can you add to your issue: the build you've used, PC specs, game format (GDI/CDI), bios used, log and the trace for the exact moment when the crash happened (are you able to reproduce this the same way everytime ?)

**Comment by inolen** [comment]
Hmph, I'm wondering if @bigboo3000 is experiencing issues similar Shoegazer is. I'll work on bisecting Shoegazer's jit issues this week.

**Comment by bigboo3000** [comment]
I'm using an i5-7200U with integrated graphics with latest build.
I'm using the standard good bios file (I don't remember the MD5 but its ok).
I'm using a .gdi tosec version converted to .chd with recent chdman.

There is nothing worth noticing in the log before the crash.

You are right the crash happens randomly, sometimes just after the sega licence screen.

Here is a trace just before a crash:
https://we.tl/PlHEYZGWOO

**Comment by bigboo3000** [comment]
it seems that https://github.com/inolen/redream/commit/57e2558da90efcd122a1d695d684ffb0d438cb5d also fixed the crash here.

**Comment by inolen** [comment]
Ah, that's probably the case.
