### ISSUE TITLE
CHD Not Currently Fully Supported?

### ISSUE THREAD

**Issue by RinMaru** [inolen/redream#217]
**Using Redream 11/12/17
Windows 10 x64
Intel i5 6402P 8GB
AMD RX 480 4GB**

So I tried to load a CHD and Redream will start up but not recognize the game disc and go straight to Bios.
Are CHD files only partially supported?

**Comment by inolen** [comment]
I'm going to need a log or something to help debug this.

It sounds like you didn't actually pass the CHD if it went to the bios, as it normally asserts when failing to load a game.

**Comment by RinMaru** [comment]
fs_set_appdir path=C:\Users\shatt\.redream
chd_parse 'TRACK:1 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:11511 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=1 fad=150 secsz=2352
chd_parse 'TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:33489 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=2 fad=11661 secsz=2352
chd_parse 'TRACK:3 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:504150 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=3 fad=45150 secsz=2352
disc_create id=SONIC ADVENTURE MK-5100050 V1.003 GD-ROM1/1
boot_load_rom loaded 'C:\Users\shatt\.redream\boot.bin'
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
bios_override_settings region=usa lang=english bcast=ntsc time=0x7fa73bd7
audio_create_device latency=92 ms/4096 frames
imgui_update_font_tex w=512 h=64
input_controller_added port=0 name=XInput Controller
dc_load path=F:\Emulators\Dreamcast\Games\Samba De Amigo.chd
chd_parse 'TRACK:1 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:600 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=1 fad=150 secsz=2352
chd_parse 'TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:44400 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=2 fad=750 secsz=2352
chd_parse 'TRACK:3 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:504150 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=3 fad=45150 secsz=2352
disc_create id=SAMBA DE AMIGO MK-5109250 V1.002 GD-ROM1/1
input_controller_added port=1 name=XInput Controller
sh4_ccn_reset
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=260 vbend=336
arm7_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
arm7_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
arm7_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36

**Comment by RinMaru** [comment]
Heres trying to load Crazy Taxi

fs_set_appdir path=C:\Users\shatt\.redream
boot_load_rom loaded 'C:\Users\shatt\.redream\boot.bin'
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
bios_override_settings region=usa lang=english bcast=ntsc time=0x7fa74085
audio_create_device latency=92 ms/4096 frames
imgui_update_font_tex w=512 h=64
dc_load path=F:\Emulators\Dreamcast\Games\Crazy Taxi.chd
chd_parse 'TRACK:1 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:600 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=1 fad=150 secsz=2352
chd_parse 'TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:44400 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=2 fad=750 secsz=2352
chd_parse 'TRACK:3 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:504150 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0' track=3 fad=45150 secsz=2352
disc_create id=CRAZY TAXI MK-51035 V1.000 GD-ROM1/1
sh4_ccn_reset
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=260 vbend=336
arm7_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
arm7_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
arm7_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
imgui_update_font_tex w=512 h=64
imgui_update_font_tex w=512 h=64

**Comment by inolen** [comment]
This doesn't seem related to the CHD file. Have you tried loading any other disc format?

**Comment by RinMaru** [comment]
nope after converting my GDI to CHD i deleted the GDI since they were taking up space but they load fine in Demul should i do a redump and send the results?

**Comment by inolen** [comment]
No, I'm just not sure what else I can do to debug this other than trying a non-CHD to start.

It seems possible it's some kind of region check failing (that's normally what kicks you back to the bios menu loading), but I'm not sure why that would be occurring only with CHD.

**Comment by RinMaru** [comment]
Crazy Taxi GDI words but CHD is Broken it will even crash as soon as you load a folder containing CHD

**Comment by inolen** [comment]
Interesting, do you have any more info on what version of CHDs these are? 

This came to mind:
https://github.com/inolen/redream/issues/176

I have a feeling you're using an older CHD format that's not working entirely for some reason. If you could try the latest version of chdman to create a a new CHD to verify the latest version works, then we can try and figure out why your particular version doesn't work.

**Comment by RinMaru** [comment]
im using CHDman from 2010

![capture](https://user-images.githubusercontent.com/15071652/32707198-2758f444-c7f0-11e7-960f-7bb7c922bcd8.PNG)

**Comment by RinMaru** [comment]
im using CHDman from 2010

Could it be i'm using chdman v5 ive heard Demul is the only emu that is compatible with v5 and others only use v4 I gather that its v5 since it uses LZMA and not deflate

if you can is there a batch file and a recommended version you can suggest im not really good with commandline stuff
![capture](https://user-images.githubusercontent.com/15071652/32707198-2758f444-c7f0-11e7-960f-7bb7c922bcd8.PNG)

**Comment by inolen** [comment]
Don't worry, I'll just try to convert and load a v4 chd soon to debug.

**Comment by RinMaru** [comment]
alright then ^^

**Comment by inolen** [comment]
I believe your CHD v4 issues should be resolved as of 00e5376562e082bf63bfe4c081bdf00d0e844bb3.

**Comment by RinMaru** [comment]
awesome ^^
