### ISSUE TITLE
controls

### ISSUE THREAD

**Issue by KoFevolution** [inolen/redream#218]
ps4 or 360 controls when pressing the circle button or B returns to the redream main menu
happens with the keyboard by pressing [
I'm sorry, I'm BR

**Comment by RinMaru** [comment]
Yea thats a GUI issue I believe and its not ready for the public. to get around this just launch a game directly by dragging it into redream or having your CHD or GDI open with Redream

**Comment by literalmente-game** [comment]
He told me on my channel that the problem was solved (he was using a very dated build, so not a real problem at all), it's safe to close the issue now.
