### ISSUE TITLE
AlienFront Online (USA) - image corruption

### ISSUE THREAD

**Issue by bigboo3000** [inolen/redream#221]
I'm not sure but I think it's a regression

redream
![image](https://user-images.githubusercontent.com/16479698/32892446-8df0f6aa-cad6-11e7-979a-00453c87c07d.png)

demul
![image](https://user-images.githubusercontent.com/16479698/32892510-b7fefd16-cad6-11e7-87e8-faa0a46657be.png)

**Comment by inolen** [comment]
This is a regression from the recent https://github.com/inolen/redream/commit/7d2e9cf3e60634762c34a005611889ffc91fdc51.

I'll need to figure out a better solution there.

Additionally, I really need to start gathering up traces for problematic areas in each game, such that the output of each trace can be automatically tested on each commit.

**Comment by inolen** [comment]
I've reverted https://github.com/inolen/redream/commit/7d2e9cf3e60634762c34a005611889ffc91fdc51 which wasn't thought out very well and committed https://github.com/inolen/redream/commit/65ae576148a3d8095430fe5da540c4e012b5b4bf which appears to be a much better step in the right direction (and fixes up this scene as well as the Mortal Kombat one).
