### ISSUE TITLE
Demolition Racer - No Exit (USA) - crash

### ISSUE THREAD

**Issue by bigboo3000** [inolen/redream#225]
intro and main menu are working fine, but when starting a game it crashes:
sh4_p4_read unexpected addr 0xec529bc8

**Comment by inolen** [comment]
This looks similar to what's happening on NHL 2K2. I need to test how memory accesses to this reserved area of p4 actually work, especially now that two games are accessing it for some reason.

@skmp any idea?

**Comment by inolen** [comment]
To note, ignoring this access makes the game work, just as it does with NHL 2K2.

**Comment by bigboo3000** [comment]
I'm not sure but I think this game was working one or two months ago.

**Comment by inolen** [comment]
Should be resolved with 4d7b4235f41f955175e450470f6e5f220b4232aa.

Fixes NHL 2K2 as well.

**Comment by bigboo3000** [comment]
Yes it's fixed
