### ISSUE TITLE
Slave Zero (USA) - Returning to bios after booting

### ISSUE THREAD

**Issue by literalmente-game** [inolen/redream#226]
GDI format used.
Windows 7
Build: https://github.com/inolen/redream/commit/a23a145a60cc376de35b3d8085d944298696f969
Log: [log.txt](https://github.com/inolen/redream/files/1484361/log.txt)

Trace (from booting until the reset): 
[0.zip](https://github.com/inolen/redream/files/1484362/0.zip)

**Comment by bigboo3000** [comment]
with hle bios it keeps rebooting in a loop.

 you can see `bios_system_vector unhandled fn=0x1` in the log (it's `fn=0x0` for other games, don't know if it's important)

**Comment by inolen** [comment]
Don't have a proper fix for this yet, but this was a great bug.

Fixing it also fixes Fur Fighters and the Sega GT slowdowns, and probably quite a few other issues.

**Comment by literalmente-game** [comment]
Fixed with build 4c4bf71
