### ISSUE TITLE
Last Hope - Hanging on the intro after booting

### ISSUE THREAD

**Issue by literalmente-game** [inolen/redream#228]
GDI format used.
Windows 7
Build: a23a145
Log: [log.txt](https://github.com/inolen/redream/files/1484388/log.txt)

**Comment by inolen** [comment]
Fixed with https://github.com/inolen/redream/commit/830274e6a9213faf99b1dd325563624b5850542c.

**Comment by literalmente-game** [comment]
Reach in-game now, fixed with https://github.com/inolen/redream/commit/830274e6a9213faf99b1dd325563624b5850542c
