### ISSUE TITLE
adjust the windows / display size when in PAL mode

### ISSUE THREAD

**Issue by bigboo3000** [inolen/redream#229]
Currently the windows / display size is 640x480 it's fine for NTSC and VGA mode.
But for PAL the bottom and the right of the screen are not displayed. In this mode the display size should be 768x576 to display everything.

**Comment by bigboo3000** [comment]
with any PAL game in 50Hz mode I think, for exemple ChuChu Rocket! PAL:

When set in 60Hz
![image](https://user-images.githubusercontent.com/16479698/32981836-f62640c2-cc7a-11e7-80be-b585e7455bc3.png)

and in 50Hz
![image](https://user-images.githubusercontent.com/16479698/32981898-4db3ce86-cc7b-11e7-8f5e-17c38898fe0e.png)

Daytona 2001

60Hz
![image](https://user-images.githubusercontent.com/16479698/32981948-6994e7d8-cc7c-11e7-882a-25425af4f5ba.png)

50Hz
![image](https://user-images.githubusercontent.com/16479698/32981935-33134f6a-cc7c-11e7-8c17-e64d985d1ac4.png)

**Comment by inolen** [comment]
This should be fixed with https://github.com/inolen/redream/commit/72120212efddcd92aacd909ca233338314acb2b9.

**Comment by bigboo3000** [comment]
hmm with this fix there are regressions

soulcalibur screen setting:
![image](https://user-images.githubusercontent.com/16479698/33242645-afe33a0c-d2d8-11e7-9d68-0a6f969370ae.png)

in 60Hz/NTSC:
![image](https://user-images.githubusercontent.com/16479698/33242656-d4ddab9e-d2d8-11e7-8612-c9539e08480a.png)

**Comment by inolen** [comment]
I was worried about regressions with this change. Hopefully SC is fixed again with latest.

**Comment by bigboo3000** [comment]
yes SC is fixed now and PAL games are displayed correctly too thanks
