### ISSUE TITLE
maple: multiple joystick support

### ISSUE THREAD

**Issue by inolen** [inolen/redream#23]
The windowing code in `ui/window.cc` uses SDL for handling joystick connections, however it only currently supports using a single joystick.

This code needs to be expanded to open multiple joysticks, as well as to append the joystick number to the generated keydown events.

After the controller number is available for the events, the  [maple](http://mc.pp.se/dc/maplebus.html) device code in `hw/maple/maple.c` needs to be expanded to allow specifying a profile per joystick, as well as creating the `struct controller` device for each connected controller.

**Comment by inolen** [comment]
While not necessary for the initial pass, it'd be fantastic to also add JoystickConnected / JoystickRemoved events similar to the KeyDown events that the maple emulation layer can use for managing its own emulated maple controller devices.

**Comment by duodenim** [comment]
I'll see if I can get some work done on this.

**Comment by inolen** [comment]
Sure, let me know if there is anything I can help you with.

**Comment by inolen** [comment]
Closing this thanks to https://github.com/inolen/redream/pull/29, will break down remaining tasks into more granular issues.
