### ISSUE TITLE
UI compiling failure (gcc 7 issue?)

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [inolen/redream#230]
I'm using gcc-7.2.1 on Fedora26.

/home/foo/aho/redream/src/ui.c: In function 'ui_file_dlg_select':
/home/foo/aho/redream/src/ui.c:651:33: error: '%s' directive output may be truncated writing up to 255 bytes into a region of size between 0 and 4095 [-Werror=format-truncation=]
       snprintf(entry, PATH_MAX, "%s" PATH_SEPARATOR "%s", path, dname);
                                 ^~~~
/home/foo/aho/redream/src/ui.c:651:54: note: format string is defined here
       snprintf(entry, PATH_MAX, "%s" PATH_SEPARATOR "%s", path, dname);
                                                      ^~
/home/foo/aho/redream/src/ui.c:651:7: note: 'snprintf' output between 2 and 4352 bytes into a destination of size 4096
       snprintf(entry, PATH_MAX, "%s" PATH_SEPARATOR "%s", path, dname);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/redream.dir/build.make:2151: CMakeFiles/redream.dir/src/ui.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:152: CMakeFiles/redream.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by inolen** [comment]
Fixed with https://github.com/inolen/redream/commit/9ac935a9e7fc9b0b2758413ad650275c23d64670.
