### ISSUE TITLE
Soul Fighter (USA) - Crashing after boot

### ISSUE THREAD

**Issue by literalmente-game** [inolen/redream#233]
GDI format used.
Windows 7
Build: https://github.com/inolen/redream/commit/3909d42ee1c237b09650476a956b58484c63d8e5
Log: [log.txt](https://github.com/inolen/redream/files/1486704/log.txt)

**Comment by inolen** [comment]
Fixed with https://github.com/inolen/redream/commit/4ad4fafb5497e6db4581cbeecc677fc1503b706c.
