### ISSUE TITLE
UI: High CPU usage

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [inolen/redream#234]
When excuting redream with no argument, the UI uses CPU arround 70%.
Is this normal?

**Comment by inolen** [comment]
This was a minor issue during development that I kept pushing off and eventually forgot to do before merging.

Fixed with https://github.com/inolen/redream/commit/c5ab4808bc285a920770b82b993d6c1ed86e5d9d.

**Comment by tokumeiwokiboushimasu** [comment]
It seems to get worse. Now CPU usage is 100%...

**Comment by inolen** [comment]
Arg, I capped it to run at 60 fps, but vsync still isn't on so it's spinning non-stop.

Will push a better fix tonight.

**Comment by inolen** [comment]
Vsync is now enabled by default: https://github.com/inolen/redream/commit/5b3e4152a514752d2244a1883215aae430243cec.

**Comment by tokumeiwokiboushimasu** [comment]
I confirmed the issue was fixed.  Thnx
