### ISSUE TITLE
Pressing B button causes returning to UI

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [inolen/redream#239]
While playing games, pressing B button causes returning to UI.
Games seems still running (sound continues, and pressing A or other buttons affects).

**Comment by KoFevolution** [comment]
drag gdi to the redream.exe executable to avoid this

**Comment by inolen** [comment]
Will take a look at this tonight.

**Comment by KoFevolution** [comment]
I'll download

**Comment by inolen** [comment]
Should be fixed with https://github.com/inolen/redream/commit/3a808a13a21b942b343fb1811401b505d2277e55.

**Comment by tokumeiwokiboushimasu** [comment]
confirmed.  thanks.
