### ISSUE TITLE
Tokyo Bus Guide - crash : TA_PARAM_OBJ_LIST_SET unsupported

### ISSUE THREAD

**Issue by bigboo3000** [inolen/redream#240]
When starting a game (I think it's all in japanese) the game crash with this in the log:
`TA_PARAM_OBJ_LIST_SET unsupported`

**Comment by bigboo3000** [comment]
now it works, maybe fixed by https://github.com/inolen/redream/commit/ff4eefa36dc4f7c457a545966648f2dcfda2877e ?

**Comment by inolen** [comment]
It's very likely that was it.
