### ISSUE TITLE
Star Wars - Episode I - Racer - corrupted graphics

### ISSUE THREAD

**Issue by bigboo3000** [inolen/redream#241]
The intro and in game FMV are corrupted.
I think it's a regression from today, I tried this game this morning and I didn't see this:
![image](https://user-images.githubusercontent.com/16479698/33085045-d1e49a54-cee3-11e7-8301-1f4ced3bbd13.png)

**Comment by inolen** [comment]
Thanks, I think I know what this is.

**Comment by inolen** [comment]
This should be fixed with latest, ended up being a Windows-only regression.
