### ISSUE TITLE
Vampire Chronicle for Matching Service sound and controller problems

### ISSUE THREAD

**Issue by 9madsheep** [inolen/redream#249]
Game: Vampire Chronicle for Matching Service v1.003 (2000)(Capcom)(NTSC)(JP)(en)[!]
OS: Win7 64bit
CPU: Core 2 Quad 9450

Problems:
1) The game suffers from sound problems on specific sound effects that makes the gameplay slow
(you can detect it in character select menu and in some battles)
2) Controller problems if i keep the right or left directional pad and spam the a and b buttons after some time the (not long) the direction pad unregisters and need to leave it and press it again
( i don't know if this is happening only in this game )
3) I thing (illusion?) that in same stages the speed is extremely fast (train stage i thing)

**Comment by inolen** [comment]
What do you mean by "need to leave it and press it again"?

**Comment by 9madsheep** [comment]
i am pressing the directional pad constantly and spam the a and b buttons  after some time the directional pad unregisters and character stops moving in that direction to make the character move again need to stop pressing the button and then press it again

**Comment by inolen** [comment]
Does that controller problem happen in other games? If not, it's likely this is a bug in the original game.

**Comment by 9madsheep** [comment]
i think it is happening on  Marvel vs. Capcom 2 and Street Fighter III too i need to test more extensively, is there an option or a way to disable sound?

**Comment by inolen** [comment]
I managed to reproduce the issue tonight, thanks a lot for the report.

**Comment by inolen** [comment]
The issues with the input not being cleared should be resolved with https://github.com/inolen/redream/commit/107f7969b0390621ed6927d4f619ac2277d6f2f5.
