### ISSUE TITLE
Enhancement - GUI 

### ISSUE THREAD

**Issue by Zetchzie** [inolen/redream#25]
So is a GUI planned in the long run?

**Comment by inolen** [comment]
Not in particular, I'd be interested in integrating with one of the many frontends instead.

However, if you mean for development then we do have some internal debug UI that's accessible by pressing f1.

**Comment by Zetchzie** [comment]
well im mean a GUI for settings and starting up games since cmd is not ideal

**Comment by inolen** [comment]
Going to close this for now, as I said, would love to integrate with one of the more popular frontends as things start to mature.
