### ISSUE TITLE
Shin Honkaku Hanafuda (Japan) doesn't load

### ISSUE THREAD

**Issue by literalmente-game** [inolen/redream#251]
GDI format used.
Windows 7
Build: 5ca08db
Log: [log.txt](https://github.com/inolen/redream/files/1503264/log.txt)

**Comment by inolen** [comment]
This looks like a bad GDI. The paths to the tracks are incorrect it seems. I've pushed a change to make this clearer in the future.

**Comment by literalmente-game** [comment]
I'll check the paths in a few minutes do confirm this

**Comment by literalmente-game** [comment]
You're correct, the GDI had a wrong file name listed, one simple change in the extention fixed it, but it's nice that the error will be easier to spot now.
