### ISSUE TITLE
[Question] So it's Pay to use?

### ISSUE THREAD

**Issue by RinMaru** [inolen/redream#253]
So Prebuilt Binaries are locked behind a one time 5$ Entry Fee? Can it still be manually compiled for free? Id gladly pay for a good emulator but why not use Patreon? Id really like to know what the plan is.

**Comment by literalmente-game** [comment]
Even the "README.md" was changed to add informations about how to compile builds yourself for each plataform, so anyone can compile it. The price is a way to pay for the convenience of downloading the already compiled builds + a way to show your support for the project.

**Comment by RinMaru** [comment]
Alright well that sounds good I wish the best for y'all and Ill throw in 5$ at some point ^^
