### ISSUE TITLE
Tony Hawk's Pro Skater 2 (USA) - crash (regression)

### ISSUE THREAD

**Issue by bigboo3000** [inolen/redream#254]
This game now crash when booting:

[C:\projects\redream\src\guest\sh4\sh4.c:53] Check failed: !(ctx->fpscr & ENABLE_MASK)
[C:\projects\redream\src\guest\sh4\sh4.c:53] FPU exceptions aren't supported

**Comment by inolen** [comment]
I checked in this assert as I was curious if any games explicitly enabled this. I've been doing a lot of work to improve FPU accuracy, will take a look at this as part of it.

**Comment by inolen** [comment]
This should no longer be a fatal error as of https://github.com/inolen/redream/commit/0b5f4eecb416488231c8b95ed80cc190534719b5.
