### ISSUE TITLE
hle bios: Confidential Mission fails to boot

### ISSUE THREAD

**Issue by kurayami6** [inolen/redream#257]
Start the game, and a few seconds later Redream closes itself.

**Comment by inolen** [comment]
Can you paste the log output (by running redream from cmd.exe, copying output when it's done).

I ran Confidential Mission here and it (from a 30 second play through) seemed ok.

![confidential_mission](https://user-images.githubusercontent.com/460296/33324260-2263f450-d41d-11e7-97c9-3f0d48be8f21.png)

**Comment by kurayami6** [comment]
![capture](https://user-images.githubusercontent.com/31968468/33342776-57ef8e80-d4d7-11e7-988b-8f82f2b63ea8.PNG)

**Comment by inolen** [comment]
I'll give it a try on Windows tonight, it may be an issue there.

In the future, the entire log is what is useful for debugging here, starting from the beginning. The easiest way to get it is to pipe stdout to a file by running `redream.exe > log.txt`.

**Comment by bigboo3000** [comment]
It works fine for me on Windows.

**Comment by kurayami6** [comment]
Thank's for looking into this. I'll be sure to specify whether I'm using real Bios or HLE in any future issue ports.

**Comment by inolen** [comment]
Not a problem. Unfortunately for now it's still best to use the real boot rom, but hopefully soon I'll have time to do another pass at making the HLE bios more compatible.

**Comment by inolen** [comment]
Closing in favor of https://github.com/inolen/redream/issues/150
