### ISSUE TITLE
Fast Striker - Wrong colors

### ISSUE THREAD

**Issue by literalmente-game** [inolen/redream#259]
Wrong color palette the entire game:

![fs](https://user-images.githubusercontent.com/24926584/33347922-a9be3808-d47b-11e7-9b7f-7e8560912706.png)

CDI format used
Windows 7
Build: d0024b8
Log: [log.txt](https://github.com/inolen/redream/files/1511841/log.txt)
Trace: unable to get a trace file, it's always empty

**Comment by inolen** [comment]
I don't have this game to test with, but I believe this should fix it https://github.com/inolen/redream/commit/621f65ca788578460bdf31e7656558bc6456e705.

Regarding the trace - currently traces only work for 3d rendering performed through the Tile Accelerator, this game is writing directly to the framebuffer. I want to refactor traces to support both routes soon.

**Comment by literalmente-game** [comment]
Fixed with https://github.com/inolen/redream/commit/621f65ca788578460bdf31e7656558bc6456e705:
![redream029 2017-11-28 21-06-57-69](https://user-images.githubusercontent.com/24926584/33349188-3d8970a8-d480-11e7-9667-2e835111dd60.png)
