### ISSUE TITLE
Redefinition of stat structure on Windows

### ISSUE THREAD

**Issue by RenatoUtsch** [inolen/redream#26]
Hi,

I was trying to compile this on Windows, and it seems that on Visual Studio 2015 (I'm on Windows 7) the compilation fails because there already exists a "struct stat", which is "redefined" in "src/core/stat.h".

This is clearly a problem with naming conflicts with your struct and a random OS struct, as renaming all "struct stat" to "struct stat2" fixed the compilation.

What would be a better name to use?

**Comment by inolen** [comment]
Ah, I added that this weekend immediately after getting Windows working for the first time in a few months.

I'd rename it `runtime_stat`.

**Comment by inolen** [comment]
Should be fixed with e0a44567267a9d6a7cb599c52792bd7e213daf88
