### ISSUE TITLE
X- input controller not recognize 

### ISSUE THREAD

**Issue by jvhellraiser** [inolen/redream#260]
Redream wont detect my Xbox one controller with wireless adapter, hopefully X-input will be implemented since this emulator looks promising, thanks for your hard work.

**Comment by inolen** [comment]
Not sure what's up here, the XInput API is supported and works as of the last time I tested in October (due to https://github.com/inolen/redream/issues/180).

Does this controller work in other games that support XInput?

**Comment by jvhellraiser** [comment]
Yes everything is working fine with other emulators i use it with Mame,Cps3,Pcsx2,Dolphin etc and is working great but when you access the input option/controller info/no controller detected
![test](https://user-images.githubusercontent.com/16488761/33356279-fc0908c0-d491-11e7-87fe-9d55f41d8043.jpg)

**Comment by inolen** [comment]
In general, they are automatically detected.

I'll have to check the Windows builds tomorrow, but unfortunately I don't actually have an XInput device myself.

**Comment by jvhellraiser** [comment]
i'll test it and report.

**Comment by inolen** [comment]
Are you downloading the binaries from redream.io or building yourself?

**Comment by jvhellraiser** [comment]
a friend pass me the emulator no sure from where is from but he said it was the latest build.

**Comment by inolen** [comment]
Yes, you're using a build that was compiled without XInput support.
