### ISSUE TITLE
Carrier (U) - Crash after booting

### ISSUE THREAD

**Issue by literalmente-game** [inolen/redream#261]
"redream.exe stopped working" error message shows up

GDI format used
Windows 7
Build: https://github.com/inolen/redream/commit/621f65ca788578460bdf31e7656558bc6456e705
Log: [log.txt](https://github.com/inolen/redream/files/1512580/log.txt)

**Comment by inolen** [comment]
Same issue as https://github.com/inolen/redream/issues/255.

**Comment by literalmente-game** [comment]
Should I close this issue and just list this game in #255 ?

**Comment by inolen** [comment]
Sounds good.
