### ISSUE TITLE
.cdi support

### ISSUE THREAD

**Issue by RenatoUtsch** [inolen/redream#27]
I was trying to start a game, but no matter what .cdi file I try the emulator only stays black.

Is there any support for .cdi files? Looking at the ReadME right now i only see .bin/.gdi support. I don't have any .gdi isos with me (and the ones I tried to run after downloading just crashed), what would be requred to support .cdi?

**Comment by RenatoUtsch** [comment]
Actually, the .gdi runs on OS X, while it crashes on Windows.

**Comment by inolen** [comment]
CDI support would be great, it's just not something that's supported right now.

Most of the gdrom io code is in https://github.com/inolen/redream/blob/master/src/hw/gdrom/disc.c, would need to add a cdi disc as well.

As far as it crashing in Windows but not OSX, make sure if you're running under the Visual Studio debugger that you disable Access Violations under Exception Settings. Segfaults are used for faster guest memory access.

**Comment by RenatoUtsch** [comment]
I was trying to run the program standalone from the command line. How can I disble access violations that way? Because Visual Studio really complains about unhandled access violations if I try to run using it (even after disabling it under Exception Settings).

**Comment by inolen** [comment]
Ah, it may be a legit crash then.

I only actively test with a few games right now (Crazy Taxi 2 and Sonic Adventure). What game are you trying out?

**Comment by RenatoUtsch** [comment]
Crazy Taxi 2.

**Comment by RenatoUtsch** [comment]
Actually I can't even debug it, it throws illegal instruction and no source available. Maybe the problem is in handwritten assembly?

The instruction where it crashed is:
000000014141B60B  vbroadcastss xmm14,xmm10

**Comment by inolen** [comment]
Hmph, I'll take a look later tonight. Does it crash immediately on boot, or after getting into a game, or ...?

**Comment by RenatoUtsch** [comment]
It doesn't even show the Dreamcast logo, but I could find printed messages on the console about loading the game.

**Comment by inolen** [comment]
As a note, I ran CT2 last night on Windows while testing and it worked at least on my system, but I wouldn't be surprised that it could break.

**Comment by inolen** [comment]
Initial cdi support was just pushed, closing this.

**Comment by legluondunet** [comment]
Hello,
does not work for me, I tested several cdi, I always obtain this message:

loading /home/legluondunet/Autres_applications/Jeux/Emulateurs/Consoles/SEGA Dreamcast/CDS/Crazy_Taxi_PAL_DC-DCP/2003-11-19-Crazy-Taxi-pal-DCP.cdi
cdi_parse version 3 detected
cdi_parse found 2 sessions
cdi_parse unsupported track mode 0x0
failed to read /home/legluondunet/Autres_applications/Jeux/Emulateurs/Consoles/SEGA Dreamcast/CDS/Crazy_Taxi_PAL_DC-DCP/2003-11-19-Crazy-Taxi-pal-DCP.cdi
failed to load /home/legluondunet/Autres_applications/Jeux/Emulateurs/Consoles/SEGA Dreamcast/CDS/Crazy_Taxi_PAL_DC-DCP/2003-11-19-Crazy-Taxi-pal-DCP.cdi
emu_clear_textures

**Comment by inolen** [comment]
I'll reopen for now, but that error looks odd, as I thought CDI's had to be mode 2 / cdrom-xa in order boot.

I only have one CDI here, and it happened to be mode 2.

**Comment by inolen** [comment]
I just pushed a potential fix with 13da62c587edbe8ff6fba61a6abbfd52011ed71d.

**Comment by legluondunet** [comment]
just tried it, always crashed with this message:

[/home/legluondunet/Autres_applications/Jeux/Emulateurs/Consoles/SEGA Dreamcast/redream/redream/src/hw/gdrom/cdi.c:43] Check failed: fmt == SECTOR_ANY || fmt == track->sector_fmt

the complete terminal log:
https://pastebin.com/cpeBMpL8

**Comment by inolen** [comment]
Question, what happens if you don't run a CDI and go to the bios menu instead? Does it ask you to set the time?

I got that same crash when I was testing, and it seemed related to that. Once I set the time the error went away.

I have a feeling the bios is doing a bad read from the CD, and I need to actually set he correct error codes vs assert'ing.

**Comment by legluondunet** [comment]
> Once I set the time the error went away.

That's right, now I can launch .cdi images, thanks.

**Comment by inolen** [comment]
Thanks for the update, I'll try and investigate that further, closing this for now.
