### ISSUE TITLE
Users must pay to access to binary builds ????

### ISSUE THREAD

**Issue by JackoboLeChocobo** [inolen/redream#272]
Purchase

A one-time payment of $5 USD provides access to all current and future binaries for Windows, Mac and Linux.

Please note, for your security our servers only store your e-mail address and a hashed version of your password. Your credit card details are never sent to us, the charge is handled entirely by Stripe. 

https://redream.io/purchase

==========

Are you serious ? The reason ? So we must compile with the source code if we want to try it if we don't pay you ?

**Comment by RinMaru** [comment]
Small price to pay for a good emulator thats actively worked on dude and helping support the dev with a small fee to afford his hobby is the least we can do. at least we can still compile it ourselves.

**Comment by JackoboLeChocobo** [comment]
Like VBA-M, another project that I will fork now to avoid the lost of a project  Not normal to force users to paid an access to a binary release of an open source project. It's not a donation, it's a product that we pay like in a supermarket.

**Comment by MerryMage** [comment]
The fwiw the GPLv3 license (which this codebase is under) [allows you to charge any fee you wish for access to binaries](https://www.gnu.org/licenses/gpl-faq.en.html#DoesTheGPLAllowDownloadFee), as long as access to the source doesn't require further payment.

**Comment by JackoboLeChocobo** [comment]
So why in the README this information is hidden before we access to the download page ? And because a license permits to do that, so it's normal on a project to apply this? Not for me. It isn't the principe of a open-source project this method.

**Comment by JackoboLeChocobo** [comment]
A normal user can to not know how to compile a source code. We are NOT all developpers in the world --"

**Comment by inolen** [comment]
Closing this as
a.) the project has moved to https://gitlab.com/inolen/redream
b.) i will write about the source code transition in the next week or two as we wrap up the current milestone
