### ISSUE TITLE
maple: uniquely name vmu save files

### ISSUE THREAD

**Issue by inolen** [inolen/redream#31]
Now that multiple controllers are supported, VMU saves need to be uniquely named so that multiple VMUs can also be supported.

Currently, every VMU instance would save to / read from the same file named `vmu.bin`:
https://github.com/inolen/redream/blob/master/src/hw/maple/vmu.c#L15

For some quick context, each input device on the Dreamcast connects to the Maple bus, which is responsible for marshaling messages between the input devices and the rest of the system. The Maple bus has 4 primary ports (corresponding to the 4 controller ports on the front of the system) and each port can connect a main unit (controller) and up to 6 additional sub units (vmu, puru puru pack, etc.).

As of 455e99ff135f976f64f122533281cbf6dbfeed59, every device has this port and unit set in its `maple_device` struct upon registration.

The port / unit should be used to uniquely name each of the VMU saves, e.g. `vmu_<port>_<unit>.bin`.

**Comment by 7oxicshadow** [comment]
Take a look at the following to see if it is the kind of thing you are looking for:

https://github.com/inolen/redream/compare/master...7oxicshadow:7oxicshadow_multi_vmu

I can confirm that it works. I have successfully transferred 4 different game saves across the different VMU's (within the Dreamcast VMU memory manager) and it appears to work well.

If you are happy that this is sufficient I will create a pull request.

**Comment by inolen** [comment]
Hey @7oxicshadow, that's it.

Left you a few comments on the change.

**Comment by 7oxicshadow** [comment]
Thanks for the review. I have updated with your changes. If your happy I will submit.

**Comment by inolen** [comment]
Yup, that looks good.

**Comment by inolen** [comment]
Fixed with @7oxicshadow PR https://github.com/inolen/redream/pull/135.
