### ISSUE TITLE
pvr: support shading instructions

### ISSUE THREAD

**Issue by inolen** [inolen/redream#35]
The Dreamcast's PowerVR chip supports 4 "shading instructions" which define how the final fragment RGBA value is calculated for a given surface.

The modes are:

| Setting | Mode | Formula |
| --------- | -------- | ----------- |
| 0          | decal  | frag.rgb = tex.rgb + offset.rgb, frag.a = tex.a |
| 1          | modulate  | frag.rgb = tex.rgb * col.rgb + offset.rgb, frag.a = tex.a |
| 2          | decal alpha  | frag.rgb = (tex.rgb * tex.a) + (col.rgb * (1 - tex.a)) + offset.rgb, frag.a = col.a |
| 3          | modulate alpha  | frag.rgb = tex.rgb * col.rgb + offset.rgb, frag.a = tex.a * col.a |

In these formulas, `frag` is the final fragment color, `tex` is the texture being sampled, and `col` / `offset` are vertex color values.

The [current fragment shader](https://github.com/inolen/redream/blob/master/src/video/ta.glsl#L37) doesn't differentiate between these modes, and renders fragments somewhat like the modulate instruction:
```
void main() {
  vec4 color = var_color;
  color *= texture(u_diffuse_map, var_diffuse_texcoord);
  color += var_offset_color;
  fragcolor = color;
}
```

We need to compile multiple versions of the fragment shader (using a preprocessor define to control the shading mode) and to then bind the appropriate shader when drawing each surface:
https://github.com/inolen/redream/blob/master/src/video/gl_backend.c#L520

To illustrate the problem, here's a problematic car in Crazy Taxi 2 captured with the tracer:
![decal_alpha](https://cloud.githubusercontent.com/assets/460296/20914838/0142b162-bb37-11e6-93b9-6170a2a38d78.png)

And here's a TA trace you can load with `redream decal_alpha.trace` to step through the scene:
http://redream.io/decal_alpha.trace

**Comment by mudlord** [comment]
I must be missing something here.

why not use surf->shade in the shader as a uniform? that way, in the shader there can be a switch statement to specify the combiner formula,

**Comment by inolen** [comment]
You're probably not missing much, I'm just not hip to modern graphics work.

Is the idea that
a.) the shader compiler will be smart and compile different versions of the shader based on that uniform
b.) gpu hardware has good branch prediction nowadays, misses are cheap

I don't really know the answer to either of those questions, hence why I suggested doing the precompiling ourselves.

**Comment by mudlord** [comment]
I daresay on modern desktop systems, since the shader will be so small, I doubt it will affect performance. Mobile GPUs on the other hand are much more sensitive to things like branching in shaders, and for them, it does make a difference.

**Comment by inolen** [comment]
@mudlord heh, I develop on an ultrabook with an intel iris 540. For this particular shader it's also probably possible to mix a uniform with step to perform the calculations without the switch / precompiling.

There is indeed a slack channel, slack.redream.io

**Comment by mudlord** [comment]
A Iris? No wonder you are concerned about performance. :)

**Comment by inolen** [comment]
Closing this with https://github.com/inolen/redream/commit/69cddefd8fcd6fd90192221cc003e7b8f5df224a

Played with a step / switch implementation, but ended up falling back to preprocessing as that code path needed to be setup for other TSP/ISP settings (`use_alpha` / `ignore_tex_alpha` / `offset`).
