### ISSUE TITLE
docs: add initial compatibility chart

### ISSUE THREAD

**Issue by inolen** [inolen/redream#37]
Many games are starting to run fairly well, it'd be nice to get an initial compatibility chart going.

I think for now a simple `doc/compatibility.md` which is just a table of all game name / comments would be a great start:

| Game | Comments |
| --- | --- |
| Bomberman Online | Fails to load 4bpp texture |
| Crazy Taxi | N/A |
| Crazy Taxi 2 | Runs great |

**Comment by Marc34** [comment]
<table>
<thead>
<tr>
<th>Game</th>
<th>Comments</th>
</tr>
</thead>
<tbody>
<tr>
<td>18 Wheeler: American Pro Trucker</td>
<td>MMU not currently supported</td>
</tr></tbody></table>

**Comment by inolen** [comment]
Hey @Marc34 , thanks for this, I'll try and add my own games I test to this and commit it soon.

**Comment by siddamastamind** [comment]
Project Justice (Pal) - Playable.  There is no music playing the background but other than that, it plays.

Marvel vs Capcom 2 - Played BEAUTIFULLY, way better than Reicast ... up until the 2nd stage, you can hear the music of the stage but no actual in game graphics show up.

**Comment by inolen** [comment]
MVC2 crash is related to https://github.com/inolen/redream/issues/81

**Comment by BPaden** [comment]
Crazy Taxi 1: Freezes after dropping off the first passenger

Gauntlet Legends - Playable, issues with broken effects and disappearing polys

**Comment by siddamastamind** [comment]
thanks @inolen .  Didn't see someone else had the relation in #81, sorry about that.  I will download some more dc games and report back when i can.  Keep up the good work bro.

**Comment by inolen** [comment]
@Marc34 going to close this issue now. I think for now we can just use Github's wiki feature for the compatibility chart so other's can edit it.

I've copied your initial compatibility chart over to:
https://github.com/inolen/redream/wiki/Compatibility
