### ISSUE TITLE
cheats: add per-game ini files 

### ISSUE THREAD

**Issue by inolen** [inolen/redream#40]
It'd be great to load up per-game ini files for that list cheats for each game like the ones being worked on over at http://assemblergames.com/l/threads/widescreen-hacks.58620/.

- [ ] generate unique id per-game. I'm not sure if there is already a unique id stored on the gd-rom itself, or if we'd have to md5 the tracks to generate our own
- [ ] add ini files to `data/games/<uid>ini`. each ini should probably look something like ```[cheats] description=cheat```
- [ ] load up ini inside of `emu_launch_gdi`
- [ ] draw debug menu inside of `emu_debug_menu` that lists each cheat which can be clicked to apply
- [ ] parse and apply the cheat codes. I believe the format of widescreen cheats above were explained in the first few pages of the thread

**Comment by duodenim** [comment]
It seems that a unique ID can be taken directly from the disc by using the product number located in IP0000.bin as shown here: https://mc.pp.se/dc/ip0000.bin.html

**Comment by inolen** [comment]
Closing this with https://github.com/inolen/redream/commit/d37dc725c6752696cbf1621d87966cbbd738d101.
