### ISSUE TITLE
Build error in linux

### ISSUE THREAD

**Issue by Marc34** [inolen/redream#42]
When I try to build redream in Ubuntu 16.10, I have an error : 

[ 86%] Linking CXX executable redream
deps/sdl2-2.0.4/libSDL2.a(SDL_waylandvideo.c.o) : Dans la fonction « wl_registry_bind » :
/usr/include/wayland-client-protocol.h:1061 : référence indéfinie vers « wl_proxy_marshal_constructor_versioned »
/usr/include/wayland-client-protocol.h:1061 : référence indéfinie vers « wl_proxy_marshal_constructor_versioned »
/usr/include/wayland-client-protocol.h:1061 : référence indéfinie vers « wl_proxy_marshal_constructor_versioned »
/usr/include/wayland-client-protocol.h:1061 : référence indéfinie vers « wl_proxy_marshal_constructor_versioned »
/usr/include/wayland-client-protocol.h:1061 : référence indéfinie vers « wl_proxy_marshal_constructor_versioned »
deps/sdl2-2.0.4/libSDL2.a(SDL_waylandvideo.c.o):/usr/include/wayland-client-protocol.h:1061 : encore plus de références indéfinies suivent vers « wl_proxy_marshal_constructor_versioned »
deps/libsoundio/libsoundio.a(jack.c.o) : Dans la fonction « soundio_jack_init » :
jack.c:(.text+0x19eb) : référence indéfinie vers « jack_set_port_rename_callback »
collect2: error: ld returned 1 exit status
CMakeFiles/redream.dir/build.make:2006 : la recette pour la cible « redream » a échouée
make[2]: *** [redream] Erreur 1
CMakeFiles/Makefile2:109 : la recette pour la cible « CMakeFiles/redream.dir/all » a échouée
make[1]: *** [CMakeFiles/redream.dir/all] Erreur 2
Makefile:127 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

**Comment by gamax92** [comment]
This is related to #28

SDL2 needs a patch to be applied so it'll build on the newer wayland API
The relevant patch is here: https://hg.libsdl.org/SDL/rev/330f500d5815
This should be applied in redream's deps/sdl2-2.0.4/ folder and then it'll compile.

**Comment by inolen** [comment]
If anyone wants to open a PR for this I'd be happy to merge it for now.

**Comment by Marc34** [comment]
Thank for your help.

**Comment by Marc34** [comment]
In fact, I still can't build redream : 

deps/libsoundio/libsoundio.a(jack.c.o) : Dans la fonction « soundio_jack_init » :
jack.c:(.text+0x19eb) : référence indéfinie vers « jack_set_port_rename_callback »
collect2: error: ld returned 1 exit status
CMakeFiles/redream.dir/build.make:2032 : la recette pour la cible « redream » a échouée
make[2]: *** [redream] Erreur 1
CMakeFiles/Makefile2:109 : la recette pour la cible « CMakeFiles/redream.dir/all » a échouée
make[1]: *** [CMakeFiles/redream.dir/all] Erreur 2
Makefile:127 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

**Comment by inolen** [comment]
Ah, that's related to: https://github.com/andrewrk/libsoundio/issues/11

The best short-term fix would be to either:
a.) disable JACK support (falling back to alsa / pulse instead) with `cmake -DENABLE_JACK=OFF ../redream`
b.) upgrade your JACK version
