### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Marc34** [inolen/redream#46]
Hi
I have no sound in Ubuntu 16.10.
I use latest binaries built.

When starting in a terminal, I get this message :

« audio_underflow_callback »

**Comment by inolen** [comment]
Sound isn't in an extremely stable state right now.

Only a few of the easier formats are decoded and played right now.  None of the Dreamcast intro audio plays, nor does any of the audio in the BIOS menus.

The only audio that normally plays right now is background music in some of the games like Crazy Taxi and Sonic Adventure.

**Comment by Marc34** [comment]
ok, thanks for the explanation.

**Comment by inolen** [comment]
No problem.
