### ISSUE TITLE
Crash emulator

### ISSUE THREAD

**Issue by weter11** [inolen/redream#47]
So, emulator can't even boot to boot. Always `Illegal instruction (core dumped)`.
I thought binaries was compiled for AVX processors, but when I compiled it, all the same.
I launched retest, it ran some tests, than: `Illegal instruction (core dumped)`

**Comment by inolen** [comment]
Any idea what the illegal instruction is? What OS?

**Comment by weter11** [comment]
Ubuntu 16.04. CPU: Athlon P320 (yes, its old).
At this moment I find only one problem from gdb:
Program terminated with signal SIGILL, Illegal instruction.
#0  0x0000000002ad043a in sh4_code ()
[Current thread is 1 (Thread 0x7fbb0ec2a700 (LWP 16139))]

**Comment by inolen** [comment]
Oh, I'm sure that's crashing due to the use of AVX instructions. I can add a runtime check for AVX support to better diagnose this in the future.

**Comment by weter11** [comment]
Ok. But when I compiled program there wasn't any AVX output, only SSE2. Anyway what to do for compiling it on my old CPU?

**Comment by inolen** [comment]
Unfortunately, there's no fallbacks for non-AVX machines currently.

**Comment by weter11** [comment]
Ok. Thanks for answer. I hope next year it will work on non AVX & maybe android machines.
As I know no any DC emu can fully emulate its hardware, so big hopes that this emulator will be the first. So I wish good luck in the development of the project. I also will trying to help something.

**Comment by inolen** [comment]
No problem, and thanks.

**Comment by inolen** [comment]
Added https://github.com/inolen/redream/commit/2c70d9fadc5232c428e28f3424f315a8ccc32b71 which should prevent this in the future.
