### ISSUE TITLE
Texture cache issue with Grandia II

### ISSUE THREAD

**Issue by gamax92** [inolen/redream#49]
Grandia II has texture cache issues in various places, one notable place where it seems to be failing consistently is the pause menu:

![incorrect](https://cloud.githubusercontent.com/assets/815145/21560771/2343c20e-ce21-11e6-8bb2-7345ce401a1a.png)
And after clearing texture cache:
![correct](https://cloud.githubusercontent.com/assets/815145/21560774/2d696a0e-ce21-11e6-988c-3e9781551ce6.png)

Trace available at [here](http://gamax92.pc-logix.com/0.trace.xz) (xz compressed)

**Comment by inolen** [comment]
Should be resolved with https://github.com/inolen/redream/commit/d70cd8e9ff1e17a1c4e66c0c633917123431c6ef
