### ISSUE TITLE
bios/flash: validate on startup

### ISSUE THREAD

**Issue by inolen** [inolen/redream#50]
There are a lot of invalid, hacked up bios / flash combinations floating around on the internet that people are going to attempt to use and experience problems with.

On startup, we should crc / md5 the bios and make sure it matches a valid bios. In addition, we should do some kind of checking on the flash to make sure it's valid.

Some notes on the flash file from a chat with @gamax92  last night:

```
[4:47 AM]  
As far as a flash validation tools goes, 0x00000, 0x10000, and 0x1C000 should all start with KATANA_FLASH____, have the correct partition number (4, 3, 2), version (0), and then followed by 0xFF
The data at 0x1A000-0x1A09F should match it's mirrored data at 0x1A0A0-0x1A13F (except for the last byte apparently)
And the CRC of each marked block in the partition bitmap should match up with the data, as well as all non marked blocks should be empty (all 0xFF)

[4:48]  
Based off of http://mc.pp.se/dc/flashmem.html and what I've see the bios write to the flash

[4:52]  
Technically you can just slap the 3 partition headers and some configuration stuff to 0x1A000 and have a valid clean flash. It'll be missing stock entries but from what my log says it never reads a large majority of the flash contents
```

**Comment by inolen** [comment]
First part of this handled by https://github.com/inolen/redream/pull/56

**Comment by altr0n** [comment]
What's left to be done here? I'd be happy to help with this

**Comment by inolen** [comment]
We have code to validate the bios thanks to @duodenim, the flash part was being handled by @gamax92, but I'm not sure where it's been left at.

He identified which parts of the flash rom were actually read from / written to, and found that it was pretty easy to generate a blank flash rom, without requiring one from the initial hardware.

**Comment by inolen** [comment]
Closing with a3929e643b4e4949dbbc68ba7735eb26a925e61b.
