### ISSUE TITLE
pvr: bad menu textures in AeroWings 2

### ISSUE THREAD

**Issue by gamax92** [inolen/redream#53]
The preview images and sky background for AeroWings 2's menus appears to be corrupted:

![badsky](https://cloud.githubusercontent.com/assets/815145/21576481/78d32c50-ceee-11e6-9b9d-4b40957801ae.png)

It should instead look somewhat more like this:
![aerowings](https://cloud.githubusercontent.com/assets/815145/21576389/66ab4a5c-ceea-11e6-9289-4ca68afe48f1.png)

Attached is a TA trace for this issue
[trace.zip](https://github.com/inolen/redream/files/679519/trace.zip)

**Comment by inolen** [comment]
Fixed with f26631c8fcd4a0e0b3c2b6334899fee1190511b7

**Comment by inolen** [comment]
@gamax92 if you have a second, could you hop on slack
