### ISSUE TITLE
(Xcode 8.2.1) 'HAVE_STRCASECMP' macro redefined (~/redream_build/src/core/config.h:5:9: 'HAVE_STRCASECMP' macro redefined)

### ISSUE THREAD

**Issue by ryanalexmartin** [inolen/redream#57]
I'm not too familiar with how these header files are configured or what this error message means, but I'll dig around and see what I can figure out.

**Comment by inolen** [comment]
I think I remember seeing this creep up back in the day because SDL used the same define. Probably should just rename the defines (which are referenced in `core/config.h.in` and `CMakeLists.txt`) to be namespaced, e.g. `REDREAM_HAVE_STRCASECMP`.

**Comment by inolen** [comment]
Going to close this out as I haven't heard anything on it in a while.
