### ISSUE TITLE
build: default to using RELWITHDEBINFO configuration

### ISSUE THREAD

**Issue by inolen** [inolen/redream#64]
When using CMake, it appears to default to the debug configuration if CMAKE_BUILD_TYPE is not explicitly passed on the command line.

In the past, I had overridden it by doing:
https://github.com/inolen/redream/commit/71d27486a252036e3e79e7f4f7fb2272a0cb0bab

However, when libsoundio was added as a dependency this broke for some reason and at the time I just removed it to work around it. It would be nice to get this back in, as the debug build isn't very playable (no fastmem, no texture cache invalidations), and many users accidentally build it their first time trying out redream.

**Comment by slowcoder** [comment]
Just did a PR to fix this. No idea why your old commit didn't work, as my PR is pretty much the same..

I have verified the PR with Sonic Adventure 2, as the intro-movie is a dead giveaway for debug builds.

**Comment by inolen** [comment]
Closed with https://github.com/inolen/redream/pull/66.
