### ISSUE TITLE
How to compile redream for macOSX ?

### ISSUE THREAD

**Issue by azoreseuropa** [inolen/redream#68]
I always compiled Citra 3DS emulator. Its easy but yours is a little bit confusion.

git clone https://github.com/inolen/redream.git
mkdir redream_build
cd redream_build

Next

# Makefile
cmake -DCMAKE_BUILD_TYPE=RELEASE ../redream

# Xcode project
cmake -G "Xcode" ../redream

No problem for me but macOS doesn't have Visual Studio then how do I do this at below ? CONFUSION:

# Visual Studio project
cmake -G "Visual Studio 14 Win64" ../redream

**Comment by inolen** [comment]
cmake generates a project file - either a Makefile, an Xcode project or a Visual Studio solution.

You only need to generate one of those. Specifically, on the Mac, you can use either the Makefile or the Xcode project to then compile the code with.

If you've generated a Makefile, you can run `make` and the project should start building.

If you've generated an Xcode project, open it up and compile through its UI.

**Comment by azoreseuropa** [comment]
Thanks but I am confused. After I am done with:

git clone https://github.com/inolen/redream.git
mkdir redream_build
cd redream_build

Next

Makefile

cmake -DCMAKE_BUILD_TYPE=RELEASE ../redream

Xcode project

cmake -G "Xcode" ../redream

Then whats next ? I am lost.

**Comment by inolen** [comment]
```
cmake -DCMAKE_BUILD_TYPE=RELEASE ../redream
make
```

**Comment by azoreseuropa** [comment]
Thanks.. Am I doing right ? After compiled it. terminal said:
Scanning dependencies of target recc
[100%] Building C object CMakeFiles/recc.dir/tools/recc/recc.c.o
[100%] Linking CXX executable recc
[100%] Built target recc
azoress-MacBook-Pro:redream_build username$ 

If so, I go to Go to Finder and type /users/ and there is two folders: redream and redream_build. Where is the one I can find to run the dreamcast games ?

**Comment by inolen** [comment]
Inside of `redream_build` is an executable called `redream`. Please note however, it is not a GUI based application, http://redream.io/docs/running contains information on running it through the command line.

**Comment by azoreseuropa** [comment]
See it. Much appreciate for your help. Can't wait for further improvement and GUI added someday. :)
