### ISSUE TITLE
Make file fail compiled in Linux alarm 3.10.18-18-ARCH  2017 armv7l GNU/Linux

### ISSUE THREAD

**Issue by aperfeito** [inolen/redream#70]
HI I tried to build this good idea emulator but after cmake generate a MakeFile in redream_build directory run **make** give this error

49%] Building C object CMakeFiles/relib.dir/src/hw/**memory.c.o**
/home/aperfeito/Downloads/redream/src/hw/**memory.c**: In function ‘reserve_address_space’:
/home/aperfeito/Downloads/redream/src/hw/memory.c:102:13: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
     *base = (uint8_t *)(1ull << i);
             ^
In file included from /home/aperfeito/Downloads/redream/src/hw/memory.c:1:0:
/home/aperfeito/Downloads/redream/src/hw/memory.h:10:28: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
 #define ADDRESS_SPACE_SIZE (UINT64_C(1) << 32)
                            ^
/home/aperfeito/Downloads/redream/src/hw/memory.c:104:31: note: in expansion of macro ‘ADDRESS_SPACE_SIZE’
     if (!reserve_pages(*base, ADDRESS_SPACE_SIZE)) {
                               ^~~~~~~~~~~~~~~~~~
/home/aperfeito/Downloads/redream/src/hw/memory.h:10:28: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
 #define ADDRESS_SPACE_SIZE (UINT64_C(1) << 32)
                            ^
/home/aperfeito/Downloads/redream/src/hw/memory.c:110:26: note: in expansion of macro ‘ADDRESS_SPACE_SIZE’
     release_pages(*base, ADDRESS_SPACE_SIZE);
                          ^~~~~~~~~~~~~~~~~~
/home/aperfeito/Downloads/redream/src/hw/memory.c: In function ‘memory_create_shmem’:
/home/aperfeito/Downloads/redream/src/hw/memory.h:10:28: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
 #define ADDRESS_SPACE_SIZE (UINT64_C(1) << 32)
                            ^
/home/aperfeito/Downloads/redream/src/hw/memory.c:193:40: note: in expansion of macro ‘ADDRESS_SPACE_SIZE’
       create_shared_memory("/redream", ADDRESS_SPACE_SIZE, ACC_READWRITE);
                                        ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/relib.dir/build.make:879: CMakeFiles/relib.dir/src/hw/memory.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by aperfeito** [comment]
And the 2 error is 

  In file included from /home/aperfeito/Downloads/redream/src/jit/backend/x64/x64_backend.cc:6:0:
/home/aperfeito/Downloads/redream/deps/xbyak-4.901/xbyak/xbyak_util.h:39:21: fatal error: cpuid.h: No such file or directory
   #include <cpuid.h>

**Comment by inolen** [comment]
Currently redream only supports the x64 architecture. It looks like you're trying to compile for armv7 which is not supported.

**Comment by aperfeito** [comment]
Hi Anthony,

    Yeah you right , but I ask you to # include ARMV support ?

     Do you understand !


Cheers

Perfeito Alexander

________________________________
De: Anthony Pesch <notifications@github.com>
Enviado: sábado, 25 de março de 2017 22:27:39
Para: inolen/redream
Cc: Alexander Nunes Perfeito; Author
Assunto: Re: [inolen/redream] Make file fail compiled in Linux alarm 3.10.18-18-ARCH 2017 armv7l GNU/Linux (#70)


Currently redream only supports the x64 architecture. It looks like you're trying to compile for armv7 which is not supported.

**Comment by inolen** [comment]
I do understand, but unfortunately I don't believe armv7 will ever be something I work on.

I'd be interested in armv8, but not 7, as I don't have a strong desire to maintain a 32-bit / 64-bit code base for this project.
