### ISSUE TITLE
xbox controller behavior (linux)

### ISSUE THREAD

**Issue by Marc34** [inolen/redream#79]
Hi

xbox controller has weird behavior (in Linux - Kubuntu 17.01).

It moves randomly up and down in menus and is unusable in games like Aqua GT, F1 World Grand Prix and some others. This xbox controller works fine with other emulators.

**Comment by inolen** [comment]
Going to work on improving some of the input code this week.

**Comment by inolen** [comment]
Give latest a try. I've swapped back to SDL now, and made the input code use its gamepad API vs the joystick API as I was using previously.

**Comment by Marc34** [comment]
Seems fine so far. Thanks !
