### ISSUE TITLE
game: Shenmue crash after intro

### ISSUE THREAD

**Issue by inolen** [inolen/redream#82]
Shenmue crashes right after the intro plays through when using the jit, yet works fine the with interpreter.

This seems to be a self-modifying code / code cache related issue.

**Comment by twinaphex** [comment]
There's similar behavior in Reicast.

You can play all the way through the garden with the 'generic JIT' (which is basically a cached interpreter). But it will crash later on there too.

**Comment by skmp** [comment]
Shenmue does do smc without i cache invalidations

**Comment by inolen** [comment]
Closing these in favor of https://github.com/inolen/redream/issues/118.
