### ISSUE TITLE
failed to open SDL audio device: No such audio device

### ISSUE THREAD

**Issue by Marc34** [inolen/redream#83]
Hi

On Ubuntu & Kubuntu 17.04, redream doesn't start anymore and I obtain this message : 

failed to open SDL audio device: No such audio device

**Comment by inolen** [comment]
Hey @Marc34 I think this is probably related to my recent replacement of libsoundio with SDL Audio. There were some SDL settings disabled at the CMake level which now have to be enabled to support SDL Audio; I just deleted / recreated my build directory to resolve it.

**Comment by Marc34** [comment]
ok, I have build redream and it works.
Thank for your great job.
