### ISSUE TITLE
GDI: start only dreamcast emu

### ISSUE THREAD

**Issue by legluondunet** [inolen/redream#87]
Hello,
I tried to launch several .gdi images games, but I have only the Dreamcast menu.
Some logs:
1) Alone in the dark - CD1 - FR
https://pastebin.com/rSvsRzpi
2) Toy commander FR
https://pastebin.com/dRaiBn2T
3) Silver FR
https://pastebin.com/18LfvkQ3

Only one of my gdi images games runs ok, Dead or Alive 2
https://pastebin.com/BvxjhywD

Thank you for your help.

**Comment by inolen** [comment]
My guess would be that you're using an NTSC bios (hence why the NTSC DoA2 ran fine).

Unfortunately, for now redream behaves like the real dreamcast and will kick you back to the main menu if there's a region mismatch between the bios and game.

**Comment by legluondunet** [comment]
Does Redream support european bios?

**Comment by inolen** [comment]
It should, yes.

With that in mind, I'm working to wrap up a commit right now that enables you to override the region, language and broadcast signal settings.

**Comment by inolen** [comment]
@legluondunet with the latest code, you can now override the region / language / broadcast mode, and the `dc_flash.bin` file is no longer required.

See http://redream.io/docs/running for the command line options to override the settings (note, you can also change them from the ui, however the changes won't take effect until after restarting redream).

**Comment by legluondunet** [comment]
works very well, thanks.
