### ISSUE TITLE
nmake compiled build - random crashes on startup

### ISSUE THREAD

**Issue by Zapeth** [inolen/redream#90]
First off I had to change a few things in the source to be able to build redream with nmake, most of them were warnings that were treated as errors due to the cmake configuration, but some stuff seems to be essential for a successful build like:
- a macro definition for a target architecture (\_AMD64\_ in this case, though I'm not sure if that macro would normally be defined in a msvc project generated from cmake)
- removal of "<core/stat.h>" header include (doesn't exist?)
- winsock initialization by calling WSAStartup() before socket() for gdb server (could have disabled the gdb server code but I wasn't sure if its essential for correct functionality of the emulator)

Here's a diff if you're curious -> https://pastebin.com/bxevxsk7

Anyway, the issue at hand are seemingly random crashes before the emulator boots up, stdout says `[...\redream\src\host\sdl_host.c:196] Check failed: res == 0` and after debugging it seems like SDL_GL_MakeCurrent() fails with SDL_GetError() returning `wglMakeCurrent(): The requested resource is in use.`

**Comment by inolen** [comment]
The Windows build hasn't been touched in a month or two, it probably needs some tlc due to quite a bit of refactoring lately.

**Comment by Zapeth** [comment]
Yeah I was suspecting something like that, just figured that I should point out the crash from SDL_GL_MakeCurrent() in case its unrelated to the refactoring.

**Comment by inolen** [comment]
Thanks!

I believe those issues creeped in during the initial libretro refactor, and my drivers on Linux aren't being quite as strict about the context creation.

**Comment by inolen** [comment]
These issues are hopefully fixed with 4e1c8ad13944d65da99961ccad01542eb8ab4a2b.

**Comment by inolen** [comment]
Also, in case you're curious, the random part of the bug was related to this:
https://github.com/inolen/redream/commit/4e1c8ad13944d65da99961ccad01542eb8ab4a2b#diff-097308c45af118b9e945e1f55cebbe3fR685

There was a race condition in that, the main thread didn't unbind the secondary render context until _after_ it created the video thread. If the video thread happened to get scheduled before the main thread unbound it, it would try to bind the same context and the error would be hit.

**Comment by Zapeth** [comment]
Thanks for the quick commits addressing these issues, the renderer seems to have been indeed fixed now.
