### ISSUE TITLE
Controller issue

### ISSUE THREAD

**Issue by Marc34** [inolen/redream#94]
There is no up and down with analog pad (but D-pad works).
My controller works with jstest-gtk and with other emulators.

Controller : Xbox 360
OS : Ubuntu 17.04

**Comment by inolen** [comment]
I assume you're talking about the left analog stick, not the right one, correct?

I can try to grab an Xbox 360 remote tonight, but not sure if I'll be able to repro. The place in code to start looking would be around https://github.com/inolen/redream/blob/master/src/host/sdl_host.c#L606.

**Comment by duodenim** [comment]
Make sure you are using the xbox360 controller profile. By default redream defaults to using button mappings for the PS4.

**Comment by inolen** [comment]
@duodenim I got rid of all that stuff now, and standardized around using SDL2's gamepad API. It has its own database of controller mappings, and gives us input standardized based on a XBOX 360 controller (e.g. we get `SDL_CONTROLLER_AXIS_LEFTX` vs joystick axis 0 now).

**Comment by duodenim** [comment]
Ah nvm then

**Comment by inolen** [comment]
No worries, I'm interested if this is a bad entry in their database, or if I've somehow broken the input handling code.

Is this broken just in a particular game, or all games?

**Comment by Marc34** [comment]
Yes, this is the left analog stick.

I have this problem in  all the games I've tried.

**Comment by inolen** [comment]
Thanks a lot for the report!

Fixed with 5af7bbde568c1b72c02036d5aaf1341a6bd5578a, a typo made it through the other day.

**Comment by Marc34** [comment]
works great now, thank!
