### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Marc34** [inolen/redream#95]
I have this error when I try to build redream : 

In file included from /home/marc/Téléchargements/redream-master/deps/sdl2-2.0.5/src/video/wayland/SDL_waylandvideo.c:34:0:
/home/marc/Téléchargements/redream-master/deps/sdl2-2.0.5/src/video/wayland/SDL_waylandvideo.c: In function ‘Wayland_CreateDevice’:
/home/marc/Téléchargements/redream-master/deps/sdl2-2.0.5/src/video/wayland/SDL_waylandopengles.h:38:38: error: ‘SDL_EGL_GetSwapInterval’ undeclared (first use in this function)
 #define Wayland_GLES_GetSwapInterval SDL_EGL_GetSwapInterval
                                      ^
/home/marc/Téléchargements/redream-master/deps/sdl2-2.0.5/src/video/wayland/SDL_waylandvideo.c:161:34: note: in expansion of macro ‘Wayland_GLES_GetSwapInterval’
     device->GL_GetSwapInterval = Wayland_GLES_GetSwapInterval;
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/marc/Téléchargements/redream-master/deps/sdl2-2.0.5/src/video/wayland/SDL_waylandopengles.h:38:38: note: each undeclared identifier is reported only once for each function it appears in
 #define Wayland_GLES_GetSwapInterval SDL_EGL_GetSwapInterval
                                      ^
/home/marc/Téléchargements/redream-master/deps/sdl2-2.0.5/src/video/wayland/SDL_waylandvideo.c:161:34: note: in expansion of macro ‘Wayland_GLES_GetSwapInterval’
     device->GL_GetSwapInterval = Wayland_GLES_GetSwapInterval;
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/marc/Téléchargements/redream-master/deps/sdl2-2.0.5/src/video/wayland/SDL_waylandopengles.h:37:38: error: ‘SDL_EGL_SetSwapInterval’ undeclared (first use in this function)
 #define Wayland_GLES_SetSwapInterval SDL_EGL_SetSwapInterval
                                      ^
/home/marc/Téléchargements/redream-master/deps/sdl2-2.0.5/src/video/wayland/SDL_waylandvideo.c:162:34: note: in expansion of macro ‘Wayland_GLES_SetSwapInterval’
     device->GL_SetSwapInterval = Wayland_GLES_SetSwapInterval;
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/marc/Téléchargements/redream-master/deps/sdl2-2.0.5/src/video/wayland/SDL_waylandopengles.h:36:36: error: ‘SDL_EGL_UnloadLibrary’ undeclared (first use in this function)
 #define Wayland_GLES_UnloadLibrary SDL_EGL_UnloadLibrary
                                    ^
/home/marc/Téléchargements/redream-master/deps/sdl2-2.0.5/src/video/wayland/SDL_waylandvideo.c:166:32: note: in expansion of macro ‘Wayland_GLES_UnloadLibrary’
     device->GL_UnloadLibrary = Wayland_GLES_UnloadLibrary;
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/marc/Téléchargements/redream-master/deps/sdl2-2.0.5/src/video/wayland/SDL_waylandopengles.h:35:37: error: ‘SDL_EGL_GetProcAddress’ undeclared (first use in this function)
 #define Wayland_GLES_GetProcAddress SDL_EGL_GetProcAddress
                                     ^
/home/marc/Téléchargements/redream-master/deps/sdl2-2.0.5/src/video/wayland/SDL_waylandvideo.c:167:33: note: in expansion of macro ‘Wayland_GLES_GetProcAddress’
     device->GL_GetProcAddress = Wayland_GLES_GetProcAddress;

Thank for your help.

**Comment by inolen** [comment]
I believe this was caused by some over-zealous changes the other day:
https://github.com/inolen/redream/commit/d5679cb219a257de853fa3189c0d0cfb5c365833

You may have to blow away your build directory for the changes to take effect.

**Comment by Marc34** [comment]
ok it works, thank!
