### ISSUE TITLE
gdrom: CHD (Compressed GDI) Support

### ISSUE THREAD

**Issue by Awakened0** [inolen/redream#96]
CHD is a great way to losslessly compress GDI files. I think in some cases they end up smaller than lossy CDIs. There is a batch utility to convert them here: https://forum.xda-developers.com/nvidia-shield/shield-qa/reicast-gdi-to-chd-t2823608

Both Reicast and NullDC support CHD, so those could be looked at when adding support for it.

**Comment by inolen** [comment]
Seems like a great feature to support.

**Comment by inolen** [comment]
For what it's worth, anyone interested in taking a stab at this could take a look at https://github.com/inolen/redream/blob/master/src/guest/gdrom/gdi.c and https://github.com/inolen/redream/blob/master/src/guest/gdrom/cdi.c to see how the existing formats are implemented.

**Comment by inolen** [comment]
Closing with 83a56f34edcd1edb535379d84d7f2fa84519c8fb.
